-- Importa a base oficial de lojas (gerado a partir de BASE.xlsx).
-- 1246 lojas.

insert into stores (code, name, type, state) values
('9282', '9282 - Matriz Campus Carrefour', 'escritorio', 'SP'),
('CSC', 'CSC - Campus Porto Alegre (408)', 'escritorio', 'RS'),
('RHX', 'RHX - Carrefour Jabaquara Núcleo RH', 'escritorio', 'SP'),
('BC', 'BC - Banco Carrefour', 'banco', 'SP'),
('RE', 'RE - Residência Executiva', 'residencia_executiva', 'SP'),
('ADN', 'ADN - Paseo Alto das Nações', 'property', 'SP'),
('BUT', 'BUT - Butantã Shopping', 'property', 'SP'),
('PAM', 'PAM - Jardim Pamplona Shopping', 'property', 'SP'),
('1192', '1192 - CD Sam''S Porto Alegre (Anexo CDMR)', 'cd', 'RS'),
('1345', '1345 - CD Sam''S Porto Alegre (Anexo CDRE)', 'cd', 'RS'),
('4946', '4946 - CD Sam''s Pernambuco (4946)', 'cd', 'PE'),
('ECJ', 'ECJ - E Commerce Cajamar', 'ecommerce', 'SP'),
('6007', '6007 - CD Sam''S Paraná (7418 (Anexo CDPH)', 'cd', 'PR'),
('CDA', 'CDA - CD Anhanguera', 'cd', 'SP'),
('CDAM', 'CDAM - CD Amazonas', 'cd', 'AM'),
('CDBA', 'CDBA - CD Salvador Pirajá (4994| 1475)', 'cd', 'BA'),
('CDBR', 'CDBR - CD Brasília', 'cd', 'DF'),
('CDD', 'CDD - CD Duque De Caxias (6008)', 'cd', 'RJ'),
('CDI', 'CDI - Express (Anexo CDA)', 'cd', 'SP'),
('CDJA', 'CDJA - CD Cajamar (4995| 7457|0070)', 'cd', 'SP'),
('CDRS', 'CDMR - CD Maxxi Rs (Sertório 7400| CDRS)', 'cd', 'RS'),
('CDMU', 'CDMU - CD Muribeca (CDMB)', 'cd', 'PE'),
('CDPE', 'CDPE - CD Pernambuco (Anexo CDMU)', 'cd', 'PE'),
('CDPH', 'CDPH - CD Pinhais (7240/ 1097)', 'cd', 'PR'),
('CDRE', 'CDRE - CD Maxxi Reiter (4996)', 'cd', 'RS'),
('CDRF', 'CDRF - CD Perecíveis Refrio (4945| 7471)', 'cd', 'SP'),
('COM', 'COM - CD Equipamentos Santo André (7049)', 'cd', 'SP'),
('PTAM', 'PTAM - Plataforma Amazonas (Anexo CDAM)', 'cd', 'AM'),
('PTBF', 'PTBF - Plataforma Pereci Friozem BA 2', 'cd', 'BA'),
('PTDC', 'PTDC - Sam''s Rio De Janeiro (Anexo CDD)', 'cd', 'RJ'),
('PTDF', 'PTDF - Plataforma Distrito Federal (Anexo CDBR)', 'cd', 'DF'),
('PTNE', 'PTNE - Plataforma Nordeste', 'cd', 'PE'),
('PTPR', 'PTPR - CD Pereci Friozem Pr (1098)', 'cd', 'PR'),
('PTSP', 'PTSP - Plataforma São Paulo', 'cd', 'SP'),
('PTRS', 'PTRS - Plataforma Reiter', 'cd', 'RS'),
('CGU', 'CGU - Drogaria Atacadão Guadalupe', 'drogaria', 'RJ'),
('DAF', 'DAF - Drogaria Anália Franco / Tatuapé', 'drogaria', 'SP'),
('DAL', 'DAL - Drogaria Alphaville', 'drogaria', 'SP'),
('DAN', 'DAN - Drogaria Anchieta', 'drogaria', 'SP'),
('DAO', 'DAO - Drogaria Hiper Santo André', 'drogaria', 'SP'),
('DAR', 'DAR - Drogaria Aricanduva', 'drogaria', 'SP'),
('DAS', 'DAS - Drogaria Santo André Shopping', 'drogaria', 'SP'),
('DBA', 'DBA - Drogaria Barra', 'drogaria', 'RJ'),
('DBB', 'DBB - Drogaria Super São Bernardo', 'drogaria', 'SP'),
('DBF', 'DBF - Drogaria Belford Roxo', 'drogaria', 'RJ'),
('DBH', 'DBH - Drogaria Bh Shopping', 'drogaria', 'MG'),
('DBK', 'DBK - Drogaria Brooklin', 'drogaria', 'SP'),
('DBN', 'DBN - Drogaria Asa Norte', 'drogaria', 'DF'),
('DBS', 'DBS - Drogaria Brasília Sul', 'drogaria', 'DF'),
('DBT', 'DBT - Drogaria Butantã', 'drogaria', 'SP'),
('DCA', 'DCA - Drogaria Canoas', 'drogaria', 'RS'),
('DCB', 'DCB - Drogaria Super Campinas', 'drogaria', 'SP'),
('DCC', 'DCC - Drogaria Campo Grande 54', 'drogaria', 'RJ'),
('DCD', 'DCD - Drogaria Campinas DE. Pedro', 'drogaria', 'SP'),
('DCG', 'DCG - Drogaria Campo Grande', 'drogaria', 'MS'),
('DCH', 'DCH - Drogaria Champagnat', 'drogaria', 'PR'),
('DCN', 'DCN - Drogaria Center Norte', 'drogaria', 'SP'),
('DCO', 'DCO - Drogaria Contagem', 'drogaria', 'MG'),
('DCP', 'DCP - Drogaria Campinas', 'drogaria', 'SP'),
('DCS', 'DCS - Drogaria Crfo Santos', 'drogaria', 'SP'),
('DCV', 'DCV - Drogaria Casa Verde', 'drogaria', 'SP'),
('DDE', 'DDE - Drogaria São Bernardo Demarchi', 'drogaria', 'SP'),
('DDF', 'DDF - Domingos Ferreira', 'drogaria', 'PE'),
('DDI', 'DDI - Drogaria Hiper Diadema', 'drogaria', 'SP'),
('DDX', 'DDX - Drogaria Duque De Caxias', 'drogaria', 'RJ'),
('DES', 'DES - Drogaria Eldorados Santos', 'drogaria', 'SP'),
('DFT', 'DFT - Drogaria Fortaleza', 'drogaria', 'CE'),
('DGA', 'DGA - Drogaria Anápolis', 'drogaria', 'GO'),
('DGD', 'DGD - Drogaria Goiânia Sudoeste', 'drogaria', 'GO'),
('DGG', 'DGG - Drogaria Giovanni Gronchi', 'drogaria', 'SP'),
('DGJ', 'DGJ - Drogaria Guarujá Hiper', 'drogaria', 'SP'),
('DGR', 'DGR - Drogaria Gravataí', 'drogaria', 'RS'),
('DGS', 'DGS - Drogaria Goiânia Sul', 'drogaria', 'GO'),
('DGT', 'DGT - Drogaria Guarulhos Dutra', 'drogaria', 'SP'),
('DGU', 'DGU - Drogaria Guarulhos', 'drogaria', 'SP'),
('DHA', 'DHA - Drogaria Bh America', 'drogaria', 'MG'),
('DIG', 'DIG - Drogaria Imigrantes', 'drogaria', 'SP'),
('DIN', 'DIN - Drogaria Super Indaiatuba', 'drogaria', 'SP'),
('DIT', 'DIT - Drogaria Interlagos', 'drogaria', 'SP'),
('DIU', 'DIU - Drogaria Super Itu', 'drogaria', 'SP'),
('DJA', 'DJA - Drogaria Jabaquara', 'drogaria', 'SP'),
('DJB', 'DJB - Drogaria João Pessoa Bancários', 'drogaria', 'PB'),
('DJC', 'DJC - Drogaria São José Dos Campos', 'drogaria', 'SP'),
('DJF', 'DJF - Drogaria Juiz De Fora', 'drogaria', 'MG'),
('DJP', 'DJP - Drogaria João Pessoa', 'drogaria', 'PB'),
('DJU', 'DJU - Drogaria Jundiaí', 'drogaria', 'SP'),
('DLI', 'DLI - Drogaria Limão', 'drogaria', 'SP'),
('DLO', 'DLO - Drogaria Londrina', 'drogaria', 'PR'),
('DLS', 'DLS - Drogaria Lagoa Santa', 'drogaria', 'MG'),
('DMB', 'DMB - Drogaria Super Morumbi', 'drogaria', 'SP'),
('DMH', 'DMH - Drogaria Manaus', 'drogaria', 'AM'),
('DMN', 'DMN - Drogaria Manilha', 'drogaria', 'RJ'),
('DMR', 'DMR - Drogaria Adrianópolis', 'drogaria', 'AM'),
('DNA', 'DNA - Drogaria Natal', 'drogaria', 'RN'),
('DNO', 'DNO - Drogaria Norte Shopping', 'drogaria', 'RJ'),
('DNT', 'DNT - Drogaria Super Interlagos', 'drogaria', 'SP'),
('DNZ', 'DNZ - Drogaria Natal Zona Norte', 'drogaria', 'RN'),
('DOS', 'DOS - Drogaria Osasco', 'drogaria', 'SP'),
('DPA', 'DPA - Drogaria Porto Alegre', 'drogaria', 'RS'),
('DPC', 'DPC - Drogaria Cambuci', 'drogaria', 'SP'),
('DPE', 'DPE - Drogaria Pêssego', 'drogaria', 'SP'),
('DPG', 'DPG - Drogaria Central Praia Grande', 'drogaria', 'SP'),
('DPH', 'DPH - Drogaria Penha', 'drogaria', 'SP'),
('DPI', 'DPI - Drogaria Pinheiros', 'drogaria', 'SP'),
('DPL', 'DPL - Drogaria Pampulha', 'drogaria', 'MG'),
('DPM', 'DPM - Drogaria Pamplona', 'drogaria', 'SP'),
('DPN', 'DPN - Drogaria Ponta Negra', 'drogaria', 'AM'),
('DPP', 'DPP - Drogaria Presidente Prudente', 'drogaria', 'SP'),
('DPR', 'DPR - Drogaria Piracicaba Hiper', 'drogaria', 'SP'),
('DPS', 'DPS - Drogaria Passos D''Areia', 'drogaria', 'RS'),
('DPV', 'DPV - Drogaria Campinas Valinhos Hiper', 'drogaria', 'SP'),
('DPW', 'DPW - Drogaria Pinhais', 'drogaria', 'PR'),
('DRA', 'DRA - Drogaria Raposo Tavares', 'drogaria', 'SP'),
('DRN', 'DRN - Drogaria Ribeirão Preto Norte', 'drogaria', 'SP'),
('DRP', 'DRP - Drogaria Ribeirão Preto Shopping', 'drogaria', 'SP'),
('DRT', 'DRT - Drogaria Torre', 'drogaria', 'PE'),
('DSA', 'DSA - Drogaria Hiper Santo André', 'drogaria', 'SP'),
('DSB', 'DSB - Drogaria São Bernardo', 'drogaria', 'SP'),
('DSC', 'DSC - Drogaria Hiper São Caetano', 'drogaria', 'SP'),
('DSD', 'DSD - Drogaria Santander', 'drogaria', 'SP'),
('DSJ', 'DSJ - Drogaria São José Rio Preto', 'drogaria', 'SP'),
('DSM', 'DSM - Drogaria Santa Maria', 'drogaria', 'RS'),
('DSN', 'DSN - Drogaria Sorocaba Norte', 'drogaria', 'SP'),
('DSO', 'DSO - Drogaria Sorocaba', 'drogaria', 'SP'),
('DSP', 'DSP - Drogaria Hiper São Bernardo', 'drogaria', 'SP'),
('DSS', 'DSS - Drogaria Rio Preto Shopping', 'drogaria', 'SP'),
('DST', 'DST - Drogaria Salto', 'drogaria', 'SP'),
('DSU', 'DSU - Drogaria Sulacap', 'drogaria', 'RJ'),
('DSV', 'DSV - Drogaria Hiper São Vicente', 'drogaria', 'SP'),
('DTA', 'DTA - Drogaria Tatuapé', 'drogaria', 'SP'),
('DTB', 'DTB - Drogaria Tamboré', 'drogaria', 'SP'),
('DTC', 'DTC - Drogaria Taubaté Charles Hiper', 'drogaria', 'SP'),
('DTG', 'DTG - Drogaria Taguatinga', 'drogaria', 'DF'),
('DTS', 'DTS - Drogaria Taboão Da Serra', 'drogaria', 'SP'),
('DTT', 'DTT - Drogaria Tietê', 'drogaria', 'SP'),
('DUB', 'DUB - Drogaria Uberlândia', 'drogaria', 'MG'),
('DVA', 'DVA - Drogaria Super Caçapava', 'drogaria', 'SP'),
('DVI', 'DVI - Drogaria Vinhedo', 'drogaria', 'SP'),
('DVL', 'DVL - Drogaria Villa Lobos', 'drogaria', 'SP'),
('DVS', 'DVS - Drogaria Vila Velha Shopping', 'drogaria', 'ES'),
('DWP', 'DWP - Drogaria Parolin', 'drogaria', 'PR'),
('FAZ', 'FAZ - Drogaria Atacadão Suzano', 'drogaria', 'SP'),
('FCP', 'FCP - Drogaria Atacadão Campinas 1', 'drogaria', 'SP'),
('FDM', 'FDM - Drogaria Boa Viagem', 'drogaria', 'PE'),
('FFV', 'FFV - Drogaria Ferraz De Vasconcelos', 'drogaria', 'SP'),
('FGU', 'FGU - Drogaria Atacadão Guarujá', 'drogaria', 'SP'),
('FIS', 'FIS - Drogaria Atacadão Inajar De Souza', 'drogaria', 'SP'),
('FIT', 'FIT - Drogaria Atacadão Itaquera', 'drogaria', 'SP'),
('FPG', 'FPG - Drogaria Atacadão Praia Grande', 'drogaria', 'SP'),
('FSR', 'FSR - Drogaria Atacadão São J. Do Rio Pto', 'drogaria', 'SP'),
('FTP', 'FTP - Drogaria Atacadão Taipas', 'drogaria', 'SP'),
('FVM', 'FVM - Drogaria Atacadão Vila Maria', 'drogaria', 'SP'),
('GON', 'GON - Drogaria Atacadão G. Norte', 'drogaria', 'GO'),
('NIG', 'NIG - Drogaria Atacadão Nova Iguaçu', 'drogaria', 'RJ'),
('MBP', 'MBP - Express Business Park', 'express', 'SP'),
('MCA', 'MCA - Express São Caetano', 'express', 'SP'),
('MCF', 'MCF - Express Canto do Forte', 'express', 'SP'),
('MCL', 'MCL - Express Aclimação', 'express', 'SP'),
('MFC', 'MFC - Express Frei Caneca', 'express', 'SP'),
('MGV', 'MGV - Express granja Viana', 'express', 'SP'),
('MHI', 'MHI - Express Higienópolis', 'express', 'SP'),
('MIB', 'MIB - Express Itaim Bibi', 'express', 'SP'),
('MJP', 'MJP - Express Jardim das Perdizes', 'express', 'SP'),
('MMO', 'MMO - Express Moema', 'express', 'SP'),
('MPE', 'MPE - Express Perdizes', 'express', 'SP'),
('MPJ', 'MPJ - Express Pateo Jahu', 'express', 'SP'),
('MPO', 'MPO - Express Paraíso', 'express', 'SP'),
('MSD', 'MSD - Express Santo André II', 'express', 'SP'),
('MVO', 'MVO - Express Vila Olímpia', 'express', 'SP'),
('MVS', 'MVS - Express Vila Suzana', 'express', 'SP'),
('XAA', 'XAA - Express Augusta Matias Aires', 'express', 'SP'),
('XAB', 'XAB - Express Alfonso Bovero', 'express', 'SP'),
('XAC', 'XAC - Express Shopping ABC', 'express', 'SP'),
('XAD', 'XAD - Express Adolfo Pinheiro', 'express', 'SP'),
('XAG', 'XAG - Express Alves Guimarães', 'express', 'SP'),
('XAI', 'XAI - Express Atrium Shopping', 'express', 'SP'),
('XAJ', 'XAJ - Express Alameda Jaú', 'express', 'SP'),
('XAM', 'XAM - Express Amazonas', 'express', 'SP'),
('XAQ', 'XAQ - Express Albuquerque Lins', 'express', 'SP'),
('XAR', 'XAR - Express Ana Rosa', 'express', 'SP'),
('XAS', 'XAS - Express Alameda Santos', 'express', 'SP'),
('XAU', 'XAU - Express Augusta', 'express', 'SP'),
('XAV', 'XAV - Express VN Melo Alves', 'express', 'SP'),
('XBA', 'XBA - Express Barão de Itapetininga', 'express', 'SP'),
('XBE', 'XBE - Express Bela Cintra', 'express', 'SP'),
('XBI', 'XBI - Express Brigadeiro Ibirapuera', 'express', 'SP'),
('XBN', 'XBN - Express Berrini II', 'express', 'SP'),
('XBP', 'XBP - Express Brigadeiro Paulista', 'express', 'SP'),
('XBR', 'XBR - Express Berrini I', 'express', 'SP'),
('XBS', 'XBS - Express São Bernardo Plaza Shopping', 'express', 'SP'),
('XBT', 'XBT - Express Shopping Boulevard Tatuapé', 'express', 'SP'),
('XBY', 'XBY - Express Bayer', 'express', 'SP'),
('XCA', 'XCA - Express Canário', 'express', 'SP'),
('XCC', 'XCC - Express Consolação Centro', 'express', 'SP'),
('XEC', 'XEC - Express Aeroporto Congonhas', 'express', 'SP'),
('XCE', 'XCE - Express Cenesp', 'express', 'SP'),
('XCL', 'XCL - Express Celso Garcia', 'express', 'SP'),
('XCN', 'XCN - Express Conjunto Nacional', 'express', 'SP'),
('XCP', 'XCP - Express Consolação Paulista', 'express', 'SP'),
('XCS', 'XCS - Express Celso Garcia II', 'express', 'SP'),
('XCT', 'XCT - Express Shopping Center 3', 'express', 'SP'),
('XCZ', 'XCZ - Express Shopping Santa Cruz', 'express', 'SP'),
('XDB', 'XDB - Express David Ben Gurion', 'express', 'SP'),
('XDM', 'XDM - Express Domingo de Moraes', 'express', 'SP'),
('XEF', 'XEF - Express Ezequiel Freire', 'express', 'SP'),
('XEQ', 'XEQ - Express Eça de Queiroz', 'express', 'SP'),
('XFF', 'XFF - Express Fagundes Filho', 'express', 'SP'),
('XFH', 'XFH - Express Flechas', 'express', 'SP'),
('XFL', 'XFL - Express Faria Lima', 'express', 'SP'),
('XFM', 'XFM - Express Francisco Matarazzo', 'express', 'SP'),
('XFR', 'XFR - Express Fradique Coutinho', 'express', 'SP'),
('XGR', 'XGR - Express Aeroporto de Guarulhos', 'express', 'SP'),
('XGT', 'XGT - Express Guarulhos TECA', 'express', 'SP'),
('XGU', 'XGU - Express Guatapará', 'express', 'SP'),
('XGV', 'XGV - Express Shopping Granja Viana', 'express', 'SP'),
('XHB', 'XHB - Express Humberto I', 'express', 'SP'),
('XHM', 'XHM - Express Henriqueta Mendes', 'express', 'SP'),
('XHP', 'XHP - Express Heitor Penteado', 'express', 'SP'),
('XHY', 'XHY - Express Horto do Ypê', 'express', 'SP'),
('XIB', 'XIB - Express Ibirapuera', 'express', 'SP'),
('XIC', 'XIC - Express Itapecerica Shopping', 'express', 'SP'),
('XIL', 'XIL - Express Imperatriz Leopoldina', 'express', 'SP'),
('XIP', 'XIP - Express Alto do Ipiranga', 'express', 'SP'),
('XIS', 'XIS - Express Praça Isai Leiner', 'express', 'SP'),
('XIT', 'XIT - Express Itapura', 'express', 'SP'),
('XJA', 'XJA - Express Jabaquara', 'express', 'SP'),
('XJB', 'XJB - Express João Batista', 'express', 'SP'),
('XJC', 'XJC - Express João Cachoeira', 'express', 'SP'),
('XJD', 'XJD - Express Vereador José Diniz', 'express', 'SP'),
('XJE', 'XJE - Express Joaquim Eugênio', 'express', 'SP'),
('XJK', 'XJK - Express Juscelino Kubistchek', 'express', 'SP'),
('XJO', 'XJO - Express João Cachoeira II', 'express', 'SP'),
('XJS', 'XJS - Express João Carlos', 'express', 'SP'),
('XLO', 'XLO - Express Alameda Lorena', 'express', 'SP'),
('XLV', 'XLV - Express Lins de Vasconcelos', 'express', 'SP'),
('XMA', 'XMA - Express Maracatins', 'express', 'SP'),
('XMC', 'XMC - Express Mourato Coelho', 'express', 'SP'),
('XME', 'XME - Express Shopping Metrópole', 'express', 'SP'),
('XMI', 'XMI - Express Shopping Metrô Itaquera', 'express', 'SP'),
('XMK', 'XMK - Express Shopping SP Market', 'express', 'SP'),
('XMO', 'XMO - Express Moema', 'express', 'SP'),
('XMR', 'XMR - Express Maria Antonia', 'express', 'SP'),
('XMT', 'XMT - Express Shopping Metrô Tucuruvi', 'express', 'SP'),
('XMV', 'XMV - Express Metrô Vila Sônia', 'express', 'SP'),
('XNG', 'XNG - Express Rio Negro II', 'express', 'SP'),
('XNS', 'XNS - Express Lapa', 'express', 'SP'),
('XNU', 'XNU - Express Shopping Nações Unidas', 'express', 'SP'),
('XOC', 'XOC - Express Mooca', 'express', 'SP'),
('XPA', 'XPA - Express Pamplona', 'express', 'SP'),
('XPB', 'XPB - Express Pacaembu', 'express', 'SP'),
('XPF', 'XPF - Express Penha da França', 'express', 'SP'),
('XPI', 'XPI - Express Piracuama', 'express', 'SP'),
('XPJ', 'XPJ - Express Padre Antônio', 'express', 'SP'),
('XPL', 'XPL - Express Paulista I', 'express', 'SP'),
('XPM', 'XPM - Express Shopping Praça da Moça', 'express', 'SP'),
('XPN', 'XPN - Express Padre Manoel', 'express', 'SP'),
('XPO', 'XPO - Express Shopping Pátio Osasco', 'express', 'SP'),
('XPS', 'XPS - Express Paineiras', 'express', 'SP'),
('XPT', 'XPT - Express Pedro de Toledo', 'express', 'SP'),
('XPU', 'XPU - Express Paulista II', 'express', 'SP'),
('XRA', 'XRA - Express Rodrigues de Abreu', 'express', 'SP'),
('XRB', 'XRB - Express Ramos Batista', 'express', 'SP'),
('XRD', 'XRD - Express Rua Diana', 'express', 'SP'),
('XRG', 'XRG - Express Rua da Graça', 'express', 'SP'),
('XRN', 'XRN - Express Rio Negro', 'express', 'SP'),
('XRP', 'XRP - Express Alameda Ribeirão Preto', 'express', 'SP'),
('XRX', 'XRX - Express Rouxinol', 'express', 'SP'),
('XSA', 'XSA - Express Sabará', 'express', 'SP'),
('XSB', 'XSB - Express São Bento', 'express', 'SP'),
('XSF', 'XSF - Express Senador Flaquer', 'express', 'SP'),
('XSJ', 'XSJ - Express São Judas', 'express', 'SP'),
('XSK', 'XSK - Express Santana Park Shopping', 'express', 'SP'),
('XSM', 'XSM - Express Shopping Mais', 'express', 'SP'),
('XSN', 'XSN - Express Santo Antônio', 'express', 'SP'),
('XSO', 'XSO - Express São Joaquim', 'express', 'SP'),
('XSQ', 'XSQ - Express Senador Queirós', 'express', 'SP'),
('XSR', 'XSR - Express Sírio Libanês', 'express', 'SP'),
('XSS', 'XSS - Express Shoppinho Santo André', 'express', 'SP'),
('XST', 'XST - Express Sete de Setembro', 'express', 'SP'),
('XTA', 'XTA - Express Tamandaré', 'express', 'SP'),
('XTE', 'XTE - Express Teodoro Sampaio II', 'express', 'SP'),
('XTI', 'XTI - Express Três Irmãos', 'express', 'SP'),
('XTO', 'XTO - Express Teodoro Oscar Freire', 'express', 'SP'),
('XTS', 'XTS - Express Teodoro Sampaio', 'express', 'SP'),
('XTT', 'XTT - Express Teodoro Sampaio 3', 'express', 'SP'),
('XTU', 'XTU - Express Tuiuti', 'express', 'SP'),
('XTZ', 'XTZ - Express Torre Z', 'express', 'SP'),
('XUS', 'XUS - Express Augusta II', 'express', 'SP'),
('XVD', 'XVD - Express Verbo Divino', 'express', 'SP'),
('XVI', 'XVI - Express Vieira de Carvalho', 'express', 'SP'),
('XVL', 'XVL - Express Vila Mariana II', 'express', 'SP'),
('XVM', 'XVM - Express Vila Mariana', 'express', 'SP'),
('XVO', 'XVO - Express Voluntários', 'express', 'SP'),
('XVS', 'XVS - Express Visconde de Inhaúma', 'express', 'SP'),
('XVV', 'XVV - Express Vista Verde', 'express', 'SP'),
('XWP', 'XWP - Express Shopping West Plaza', 'express', 'SP'),
('XXA', 'XXA - Express Xavier de Toledo', 'express', 'SP'),
('XAE', 'XAE - Express Hospital Israelita Albert Einstein', 'express_autonoma', 'SP'),
('XCD', 'XCD - Casa das Caldeiras', 'express_autonoma', 'SP'),
('XCF', 'XCF - Novo Jardim Family', 'express_autonoma', 'SP');

insert into stores (code, name, type, state) values
('XCM', 'XCM - Morada dos Clássicos', 'express_autonoma', 'SP'),
('XCY', 'XCY - Pateo Catalunya', 'express_autonoma', 'SP'),
('XDP', 'XDP - Domo Prime', 'express_autonoma', 'SP'),
('XGA', 'XGA - California Garden', 'express_autonoma', 'SP'),
('XHA', 'XHA - Dez Anhaia Mello', 'express_autonoma', 'SP'),
('XHC', 'XHC - São Camilo', 'express_autonoma', 'SP'),
('XHS', 'XHS - Hospital São Camilo - Santana', 'express_autonoma', 'SP'),
('XHZ', 'XHZ - Chácara Santa Cruz', 'express_autonoma', 'SP'),
('XIA', 'XIA - Interclube Alpha e Beta', 'express_autonoma', 'SP'),
('XIG', 'XIG - Interclube Gama', 'express_autonoma', 'SP'),
('XJV', 'XJV - Clube Jd Vila Maria', 'express_autonoma', 'SP'),
('XLC', 'XLC - Living Magic', 'express_autonoma', 'SP'),
('XLM', 'XLM - Leroy Merlin', 'express_autonoma', 'SP'),
('XMF', 'XMF - Moov Freguesia', 'express_autonoma', 'SP'),
('XMG', 'XMG - LIVING MAGIC II', 'express_autonoma', 'SP'),
('XMP', 'XMP - Condomínio Mansão Imperial', 'express_autonoma', 'SP'),
('XMS', 'XMS - Misti Morumbi', 'express_autonoma', 'SP'),
('XNB', 'XNB - Nova Butantã', 'express_autonoma', 'SP'),
('XOS', 'XOS - Piscine Osasco', 'express_autonoma', 'SP'),
('XPK', 'XPK - Central Park Prime', 'express_autonoma', 'SP'),
('XPR', 'XPR - Praça das Águas', 'express_autonoma', 'SP'),
('XQH', 'XQH - Quality House Lapa', 'express_autonoma', 'SP'),
('XRF', 'XRF - Condomínio Refuge', 'express_autonoma', 'SP'),
('XRS', 'XRS - Piscine Brás', 'express_autonoma', 'SP'),
('XTG', 'XTG - The Gate', 'express_autonoma', 'SP'),
('XTJ', 'XTJ - Start Jardim Clube', 'express_autonoma', 'SP'),
('XTM', 'XTM - Tamboré Matriz', 'express_autonoma', 'SP'),
('XTR', 'XTR - Express Santander', 'express_autonoma', 'SP'),
('XUT', 'XUT - Cult', 'express_autonoma', 'SP'),
('XVP', 'XVP - Vereda Paraíso', 'express_autonoma', 'SP'),
('XVT', 'XVT - Vertentes', 'express_autonoma', 'SP'),
('BAN', 'BAN - Brasília Asa Norte', 'hiper', 'DF'),
('BCS', 'BCS - Hiper Santa Cruz do Sul', 'hiper', 'RS'),
('BCV', 'BCV - Casa Verde', 'hiper', 'SP'),
('BDP', 'BDP - Hiper Campo DE. Pedro', 'hiper', 'SP'),
('BES', 'BES - Hiper Esteio', 'hiper', 'RS'),
('BFB', 'BFB - Hiper Bezerra de Menezes', 'hiper', 'CE'),
('BGU', 'BGU - Guarulhos Dutra', 'hiper', 'SP'),
('BHA', 'BHA - BH América', 'hiper', 'MG'),
('BHC', 'BHC - Contagem', 'hiper', 'MG'),
('BHP', 'BHP - Hiper Pampulha', 'hiper', 'MG'),
('BHS', 'BHS - BH Shopping', 'hiper', 'MG'),
('BLP', 'BLP - Hiper São Leopoldo', 'hiper', 'RS'),
('BPS', 'BPS - Hiper Sertório', 'hiper', 'RS'),
('BRG', 'BRG - Hiper Rio Grande', 'hiper', 'RS'),
('BRP', 'BRP - Hiper Ribeirão Preto', 'hiper', 'SP'),
('BSA', 'BSA - Santo André Shopping', 'hiper', 'SP'),
('BSB', 'BSB - Brasília Sul', 'hiper', 'DF'),
('BSI', 'BSI - Hiper Salvador Iguatemi', 'hiper', 'BA'),
('BSP', 'BSP - Santos Praiamar', 'hiper', 'SP'),
('BSR', 'BSR - Hiper Salvador Norte', 'hiper', 'BA'),
('BTR', 'BTR - Hiper Teresina', 'hiper', 'PI'),
('BVC', 'BVC - Hiper Vitória da Conquista', 'hiper', 'BA'),
('CAI', 'CAI - Iguatemi Campinas (ECP)', 'hiper', 'SP'),
('CAL', 'CAL - Alcântara', 'hiper', 'RJ'),
('CAR', 'CAR - Hiper Cabral (BCA)', 'hiper', 'PR'),
('CBR', 'CBR - Belford Roxo', 'hiper', 'RJ'),
('CCP', 'CCP - Campo Grande 54', 'hiper', 'RJ'),
('CGD', 'CGD - Campo Grande (ECG)', 'hiper', 'MS'),
('EBS', 'EBS - Side Store (ecommerce BSB)', 'ecommerce', 'DF'),
('CMS', 'CMS - Manaus Shopping', 'hiper', 'AM'),
('CNS', 'CNS - Canoas', 'hiper', 'RS'),
('CPS', 'CPS - Campinas DE. Pedro', 'hiper', 'SP'),
('CPV', 'CPV - Campinas Valinhos', 'hiper', 'SP'),
('CRE', 'CRE - Hiper Avenida Recife (BRE)', 'hiper', 'PE'),
('CSS', 'CSS - São José Rio Preto Shopp', 'hiper', 'SP'),
('CWB', 'CWB - Pinhais', 'hiper', 'PR'),
('CWC', 'CWC - Champagnat', 'hiper', 'PR'),
('CWP', 'CWP - Parolin', 'hiper', 'PR'),
('CXS', 'CXS - Caxias', 'hiper', 'RS'),
('DDC', 'DDC - Duque de Caxias Brig', 'hiper', 'RJ'),
('ECN', 'ECN - Center Norte', 'hiper', 'SP'),
('ERB', 'ERB - Rebouças (ERE)', 'hiper', 'SP'),
('GOP', 'GOP - Anápolis', 'hiper', 'GO'),
('GOS', 'GOS - Goiânia Sul', 'hiper', 'GO'),
('GRU', 'GRU - Guarulhos', 'hiper', 'SP'),
('ECV', 'ECV - Side Store (ecommerce CPV)', 'ecommerce', 'SP'),
('GRV', 'GRV - Gravataí', 'hiper', 'RS'),
('GSD', 'GSD - Goiânia Sudoeste', 'hiper', 'GO'),
('GUA', 'GUA - Guarujá', 'hiper', 'SP'),
('HAC', 'HAC - Hiper Águas Claras (BAC)', 'hiper', 'DF'),
('HBO', 'HBO - Hiper Camboriú (BBO)', 'hiper', 'SC'),
('HBT', 'HBT - Hiper Tamboré (BBT)', 'hiper', 'SP'),
('HCG', 'HCG - Hiper Campos Goytacazes (BCG)', 'hiper', 'RJ'),
('HCO', 'HCO - Hiper Campinas Outlet (BCO)', 'hiper', 'SP'),
('HCP', 'HCP - Hiper Campina Grande (BCP)', 'hiper', 'PB'),
('HFL', 'HFL - Hiper Florianópolis Shop (BFL)', 'hiper', 'SC'),
('HIT', 'HIT - Hiper Itabuna (BIT)', 'hiper', 'BA'),
('HJB', 'HJB - Hiper Guararapes (BJG|HJG)', 'hiper', 'PE'),
('HMC', 'HMC - Hiper Macaé (BMC)', 'hiper', 'RJ'),
('HMS', 'HMS - Hiper Mossoró (BMS)', 'hiper', 'RN'),
('HNH', 'HNH - Nicolau Becker (BNH| 1806)', 'hiper', 'RS'),
('HNL', 'HNL - Hiper N S Lourdes (BNL| 025)', 'hiper', 'RS'),
('HOS', 'HOS - Hiper Osasco (BOS)', 'hiper', 'SP'),
('HPC', 'HPC - Hiper Cristal (BPC)', 'hiper', 'RS'),
('HPE', 'HPE - Hiper Petrolina (BPE)', 'hiper', 'PE'),
('HPR', 'HPR - Hiper Pelotas (BPR)', 'hiper', 'RS'),
('HTC', 'HTC - Hiper Tacaruna (BTC)', 'hiper', 'PE'),
('HVA', 'HVA - Hiper Viamão (BVA)', 'hiper', 'RS'),
('HWL', 'HWL - Hiper Washington Luís (BWL)', 'hiper', 'SP'),
('JDI', 'JDI - Jundiaí', 'hiper', 'SP'),
('JFO', 'JFO - Juiz de Fora', 'hiper', 'MG'),
('JPB', 'JPB - JP Cidade dos Bancários', 'hiper', 'PB'),
('JPE', 'JPE - João Pessoa', 'hiper', 'PB'),
('LDB', 'LDB - Londrina', 'hiper', 'PR'),
('MAD', 'MAD - Manaus Adrianópolis', 'hiper', 'AM'),
('MJT', 'MJT - Hiper Jatiúca (BMJ)', 'hiper', 'AL'),
('MNS', 'MNS - Manaus Hiper', 'hiper', 'AM'),
('MPN', 'MPN - Ponta Negra', 'hiper', 'AM'),
('NTL', 'NTL - Natal', 'hiper', 'RN'),
('NZN', 'NZN - Natal Zona Norte', 'hiper', 'RN'),
('OSC', 'OSC - Osasco', 'hiper', 'SP'),
('PDT', 'PDT - Presidente Prudente (EPP)', 'hiper', 'SP'),
('PIR', 'PIR - Piracicaba', 'hiper', 'SP'),
('PLN', 'PLN - Pamplona (EPL)', 'hiper', 'SP'),
('POA', 'POA - Porto Alegre', 'hiper', 'RS'),
('POR', 'POR - Hiper Portão (BPO)', 'hiper', 'PR'),
('PPA', 'PPA - Passos DE Areia', 'hiper', 'RS'),
('RDM', 'RDM - Domingos Ferreira', 'hiper', 'PE'),
('REC', 'REC - Recife', 'hiper', 'PE'),
('RJB', 'RJB - Barra', 'hiper', 'RJ'),
('RJD', 'RJD - Duque de Caxias', 'hiper', 'RJ'),
('RJJ', 'RJJ - Sulacap', 'hiper', 'RJ'),
('RJM', 'RJM - Manilha', 'hiper', 'RJ'),
('RJS', 'RJS - Norte Shopping', 'hiper', 'RJ'),
('RPN', 'RPN - Ribeirão Preto Norte', 'hiper', 'SP'),
('RPS', 'RPS - Ribeirão Preto', 'hiper', 'SP'),
('SAN', 'SAN - Santos (EST)', 'hiper', 'SP'),
('SAV', 'SAV - São Vicente', 'hiper', 'SP'),
('SBC', 'SBC - São Bernardo', 'hiper', 'SP'),
('SBD', 'SBD - Demarchi', 'hiper', 'SP'),
('SBK', 'SBK - Brooklin', 'hiper', 'SP'),
('SBP', 'SBP - São Bernardo Paulicéia', 'hiper', 'SP'),
('SCS', 'SCS - São Caetano', 'hiper', 'SP'),
('SJC', 'SJC - São José dos Campos', 'hiper', 'SP'),
('SJP', 'SJP - São José Rio Preto', 'hiper', 'SP'),
('SMA', 'SMA - Santa Maria', 'hiper', 'RS'),
('SON', 'SON - Sorocaba Norte', 'hiper', 'SP'),
('SOR', 'SOR - Sorocaba', 'hiper', 'SP'),
('SPA', 'SPA - Anchieta', 'hiper', 'SP'),
('SPB', 'SPB - Butantã', 'hiper', 'SP'),
('SPC', 'SPC - Cambuci Lion', 'hiper', 'SP'),
('SPE', 'SPE - Pêssego', 'hiper', 'SP'),
('SPG', 'SPG - Giovanni Gronchi', 'hiper', 'SP'),
('SPI', 'SPI - Interlagos', 'hiper', 'SP'),
('SPL', 'SPL - Limão', 'hiper', 'SP'),
('SPO', 'SPO - Raposo Tavares', 'hiper', 'SP'),
('SPP', 'SPP - Pinheiros', 'hiper', 'SP'),
('SPR', 'SPR - Aricanduva', 'hiper', 'SP'),
('SPS', 'SPS - Imigrantes', 'hiper', 'SP'),
('SPT', 'SPT - Tietê', 'hiper', 'SP'),
('STA', 'STA - Santo André', 'hiper', 'SP'),
('STO', 'STO - Santo André Oratório', 'hiper', 'SP'),
('STS', 'STS - Taboão da Serra', 'hiper', 'SP'),
('TAU', 'TAU - Taubaté Charles', 'hiper', 'SP'),
('TBE', 'TBE - Tamboré', 'hiper', 'SP'),
('TTE', 'TTE - Anália Franco', 'hiper', 'SP'),
('ETT', 'ETT - Side Store (ecommerce TTE)', 'ecommerce', 'SP'),
('UBL', 'UBL - Uberlândia', 'hiper', 'MG'),
('VVS', 'VVS - Vila Velha Shopping', 'hiper', 'ES'),
('ESV', 'ESV - Posto Vila Velha', 'posto', 'ES'),
('PAB', 'PAB - Posto Atacadão Ananindeua/Belem (PBL/Makro)', 'posto', 'PA'),
('PAC', 'PAC - Posto Automóvel Clube', 'posto', 'RJ'),
('PAD', 'PAD - Posto Sam''s Santo André', 'posto', 'SP'),
('PAG', 'PAG - Posto Guarujá Atacadão', 'posto', 'SP'),
('PAJ', 'PAJ - Posto Atacadao Juiz De Fora', 'posto', 'MG'),
('PAM_P', 'PAM - Posto Maceió', 'posto', 'AL'),
('PAN', 'PAN - Posto Anchieta', 'posto', 'SP'),
('PAP', 'PAP - Posto Goiânia Anápolis', 'posto', 'GO'),
('PAT', 'PAT - Posto Atacadão Taubaté', 'posto', 'SP'),
('PBA', 'PBA - Posto Barra Hiper', 'posto', 'RJ'),
('PBC', 'PBC - Posto São Bernardo Vergueiro', 'posto', 'SP'),
('PBD', 'PBD - Posto São Bernardo Demarchi', 'posto', 'SP'),
('PBL', 'PBL - Posto Belém', 'posto', 'PA'),
('PBN', 'PBN - Posto São Bernardo Do Campo', 'posto', 'SP'),
('PBO', 'PBO - Posto Camboriú (PBB)', 'posto', 'SC'),
('PBP', 'PBP - Posto São Bernardo Paulicéia', 'posto', 'SP'),
('PBR', 'PBR - Posto Belford Roxo', 'posto', 'RJ'),
('PBV', 'PBV - Posto Bauru (PBU| PBS)', 'posto', 'SP'),
('PCA', 'PCA - Posto Cambuci', 'posto', 'SP'),
('PCB', 'PCB - Posto Cuiabá', 'posto', 'MT'),
('PCC', 'PCC - Posto Contagem', 'posto', 'MG'),
('PCG', 'PCG - Posto Campo Grande', 'posto', 'RJ'),
('PCI', 'PCI - Posto Piracicaba Sams (PPS)', 'posto', 'SP'),
('PCJ', 'PCJ - Posto Juiz De Fora', 'posto', 'MG'),
('PCL', 'PCL - Posto Limão', 'posto', 'SP'),
('PCN', 'PCN - Posto Canoas', 'posto', 'RS'),
('PCP', 'PCP - Posto Campinas Dom Pedro', 'posto', 'SP'),
('PCR', 'PCR - Posto Recife', 'posto', 'PE'),
('PCT', 'PCT - Posto Taboão', 'posto', 'SP'),
('PCU', 'PCU - Posto Uberlândia', 'posto', 'MG'),
('PCV', 'PCV - Posto Caçapava', 'posto', 'SP'),
('PCW', 'PCW - Posto Curitiba Pinhais', 'posto', 'PR'),
('PCX', 'PCX - Posto Caxias', 'posto', 'RS'),
('PCZ', 'PCZ - Posto Sta Cruz Do Sul', 'posto', 'RS'),
('PDI', 'PDI - Posto Diadema', 'posto', 'SP'),
('PDQ', 'PDQ - Posto Duque De Caxias', 'posto', 'RJ'),
('PFR', 'PFR - Posto Franca', 'posto', 'SP'),
('PGA', 'PGA - Posto Goiânia Aparecida', 'posto', 'GO'),
('PGB', 'PGB - Posto Gravataí  Cohab (PGC|912)', 'posto', 'RS'),
('PGD', 'PGD - Posto Goiânia Sudoeste', 'posto', 'GO'),
('PGH', 'PGH - Posto Garanhuns', 'posto', 'PE'),
('PGN', 'PGN - Posto Goiânia Norte', 'posto', 'GO'),
('PGO', 'PGO - Posto Atacadão Goiânia Aparecida ( Makro)', 'posto', 'GO'),
('PGP', 'PGP - Posto Guadalupe', 'posto', 'RJ'),
('PGR', 'PGR - Posto Guarulhos', 'posto', 'SP'),
('PGS', 'PGS - Posto Goiânia Sul', 'posto', 'GO'),
('PGT', 'PGT - Posto Gravataí', 'posto', 'RS'),
('PGU', 'PGU - Posto Guarujá', 'posto', 'SP'),
('PGV', 'PGV - Posto Atacadão Gravataí', 'posto', 'RS'),
('PIM', 'PIM - Posto Atacadão Imperatriz', 'posto', 'MA'),
('PIT', 'PIT - Posto Itu', 'posto', 'SP'),
('PJB', 'PJB - Posto Jabaquara', 'posto', 'SP'),
('PJC', 'PJC - Posto São José Dos Campos', 'posto', 'SP'),
('PJD', 'PJD - Posto Jundiaí', 'posto', 'SP'),
('PJP', 'PJP - Posto João Pessoa', 'posto', 'PB'),
('PLA', 'PLA - Posto Linha Amarela (1190| 915)', 'posto', 'RJ'),
('PLD', 'PLD - Posto Londrina', 'posto', 'PR'),
('PLI', 'PLI - Posto Limeira (PLM)', 'posto', 'SP'),
('PMA', 'PMA - Posto Manilha', 'posto', 'RJ'),
('PMB', 'PMB - Posto Barra Atacadão', 'posto', 'RJ'),
('PMC', 'PMC - Posto Atacadão Cuiabá ( Makro| PCB)', 'posto', 'MT'),
('PMF', 'PMF - Posto Florianópolis', 'posto', 'SC'),
('PMG', 'PMG - Posto Goiânia', 'posto', 'GO'),
('PMJ', 'PMJ - Posto Joinvile', 'posto', 'SC'),
('PML', 'PML - Posto São Leopoldo', 'posto', 'RS'),
('PMN', 'PMN - Posto Nova Iguaçu Makro', 'posto', 'RJ'),
('PMP', 'PMP - Posto Pinhas Makro', 'posto', 'PR'),
('PMR', 'PMR - Posto Atacadão Marília', 'posto', 'SP'),
('PMT', 'PMT - Posto Teresina', 'posto', 'PI'),
('PNI', 'PNI - Posto Nova Iguaçu', 'posto', 'RJ'),
('PNN', 'PNN - Posto Natal Zona Norte', 'posto', 'RN'),
('PNR', 'PNR - Posto Niterói', 'posto', 'RJ'),
('POS', 'POS - Posto Osasco', 'posto', 'SP'),
('PPC', 'PPC - Posto Piracicaba', 'posto', 'SP'),
('PPD', 'PPD - Posto Passo DE´Areia', 'posto', 'RS'),
('PPO', 'PPO - Posto Porto Alegre (Ipiranga)', 'posto', 'RS'),
('PPP', 'PPP - Posto Pampulha', 'posto', 'MG'),
('PPV', 'PPV - Posto Atacadão Porto Velho', 'posto', 'RO'),
('PRA', 'PRA - Posto Araras (906/ PAA)', 'posto', 'SP'),
('PRF', 'PRF - Posto Recife Makro', 'posto', 'PE'),
('PRO', 'PRO - Posto Santa Maria Patronato (PPT)', 'posto', 'RS'),
('PRP', 'PRP - Posto Ribeirão Preto Norte', 'posto', 'SP'),
('PRT', 'PRT - Posto Raposo Tavares', 'posto', 'SP'),
('PSA', 'PSA - Posto Santo André', 'posto', 'SP'),
('PSC', 'PSC - Posto São Caetano Do Sul', 'posto', 'SP'),
('PSG', 'PSG - Posto Pêssego', 'posto', 'SP'),
('PSI', 'PSI - Posto Sinop', 'posto', 'MT'),
('PSJ', 'PSJ - Posto São José Dos Campos II', 'posto', 'SP'),
('PSK', 'PSK - Posto Sapucaia Do Sul', 'posto', 'RS'),
('PSM', 'PSM - Posto São Miguel', 'posto', 'SP'),
('PSN', 'PSN - Posto Sorocaba Norte', 'posto', 'SP'),
('PSO', 'PSO - Posto Santo André Oratório', 'posto', 'SP'),
('PSP', 'PSP - Posto São José Do Rio Preto', 'posto', 'SP'),
('PSR', 'PSR - Posto Serra', 'posto', 'ES'),
('PSS', 'PSS - Posto Votorantim/Shopping (Sorocaba)', 'posto', 'SP'),
('PST', 'PST - Posto Salto', 'posto', 'SP'),
('PSU', 'PSU - Posto Sulacap', 'posto', 'RJ'),
('PSV', 'PSV - Posto São Vicente', 'posto', 'SP'),
('PSZ', 'PSZ - Posto Suzano', 'posto', 'SP'),
('PTA', 'PTA - Posto Tamboré', 'posto', 'SP'),
('PTG', 'PTG - Posto Contagem (PCO| 940)', 'posto', 'MG'),
('PTI', 'PTI - Posto Tietê', 'posto', 'SP'),
('PTO', 'PTO - Posto Patos', 'posto', 'PB'),
('PTP', 'PTP - Posto Tatuape', 'posto', 'SP'),
('PTT', 'PTT - Posto Taubaté', 'posto', 'SP'),
('PVA', 'PVA - Posto Valparaiso', 'posto', 'GO'),
('PVD', 'PVD - Posto Casa Verde', 'posto', 'SP'),
('PVG', 'PVG - Posto Atacadão Várzea Grande', 'posto', 'MT'),
('PVL', 'PVL - Posto Vilhena', 'posto', 'RO'),
('4001', '4001 - Sam''s Blumenau (BLS)', 'sams_club', 'SC'),
('4006', '4006 - Sam''s Cotia (Granja Viana) (GVS)', 'sams_club', 'SP'),
('4007', '4007 - Sam''s Barra Shopping Sul (Cristal) (PAC| BPC)', 'sams_club', 'RS'),
('4014', '4014 - Sam''s Teresina (TNS)', 'sams_club', 'PI'),
('4015', '4015 - Sam''s Curitiba Torres (CTS)', 'sams_club', 'PR'),
('4017', '4017 - Sam''s João Pessoa Bessa (JPS)', 'sams_club', 'PB'),
('4018', '4018 - Sam''s São José do Rio Preto (JRS)', 'sams_club', 'SP'),
('4021', '4021 - Sam''s Lauro de Freitas (LFB)', 'sams_club', 'BA'),
('4033', '4033 - Sam''s Bauru (BAS)', 'sams_club', 'SP'),
('4039', '4039 - Sams'' Franca (FRA)', 'sams_club', 'SP'),
('4040', '4040 - Sam''s Caxias do Sul (CIS)', 'sams_club', 'RS'),
('4044', '4044 - Sam''s Americana (AMS)', 'sams_club', 'SP'),
('4053', '4053 - Sam''s Jabaquara (SJA| JAB)', 'sams_club', 'SP'),
('4054', '4054 - Sam''s Pampulha (BHD| PMP)', 'sams_club', 'MG'),
('4060', '4060 - Sam''s Barra (BAR)', 'sams_club', 'RJ'),
('4063', '4063 - Sam''s Florianópolis (Capoeiras) (CAF)', 'sams_club', 'SC'),
('4066', '4066 - Sam''s Bonocô (BON)', 'sams_club', 'BA'),
('4067', '4067 - Sam''s Indaiatuba (IND)', 'sams_club', 'SP'),
('4069', '4069 - Sam''s Campus', 'sams_club', 'SP'),
('4078', '4078 - Sam''s Uberlândia (SCSS) (Antigo BUS)', 'sams_club', 'MG'),
('4083', '4083 - Sam''s Maceió Farol (SCAF) (Antigo BMF)', 'sams_club', 'AL'),
('4085', '4085 - Sam''s Feira De Santana (SCSF) (Antigo BFE)', 'sams_club', 'BA'),
('4086', '4086 - Sam''s Fortaleza Washington Soares (SCWS) (Antigo BFW)', 'sams_club', 'CE'),
('4415', '4415 - Sam''s Vila Leopoldina (VLS)', 'sams_club', 'SP'),
('4672', '4672 - Sam''s Joinville Anita Garibaldi (BJO| America JLS)', 'sams_club', 'SC'),
('4673', '4673 - Sam''s Sorocaba (SBS)', 'sams_club', 'SP'),
('4675', '4675 - Sam''s Campo Grande (CGS)', 'sams_club', 'MS'),
('4676', '4676 - Sam''s Aracaju (AJS)', 'sams_club', 'SE'),
('4677', '4677 - Sam''s Piracicaba (PRS)', 'sams_club', 'SP'),
('4678', '4678 - Sam''s Presidente Prudente (PTS)', 'sams_club', 'SP');

insert into stores (code, name, type, state) values
('4825', '4825 - Sam''s Bom Retiro (BBR)', 'sams_club', 'SP'),
('4857', '4857 - Sam''s Barigui (BGS)', 'sams_club', 'PR'),
('4918', '4918 - Sam''s Radial Leste (RLS)', 'sams_club', 'SP'),
('4929', '4929 - Sam''s Asa Norte (BNS)', 'sams_club', 'DF'),
('4930', '4930 - Sam''s Morumbi (MBS)', 'sams_club', 'SP'),
('4931', '4931 - Sam''s São José dos Campos (JCS)', 'sams_club', 'SP'),
('4932', '4932 - Sam''s Tamboré (TBS)', 'sams_club', 'SP'),
('4933', '4933 - Sam''s Vitória (VTS)', 'sams_club', 'ES'),
('4934', '4934 - Sam''s Goiânia (GNS)', 'sams_club', 'GO'),
('4935', '4935 - Sam''s Brasília (BRS)', 'sams_club', 'DF'),
('4936', '4936 - Sam''s Salvador (SVS)', 'sams_club', 'BA'),
('4937', '4937 - Sam''s Maceió (MCS)', 'sams_club', 'AL'),
('4938', '4938 - Sam''s Campinas (CAS)', 'sams_club', 'SP'),
('4940', '4940 - Sam''s Guarulhos (GUS)', 'sams_club', 'SP'),
('4941', '4941 - Sam''s Recife (RFS)', 'sams_club', 'PE'),
('4943', '4943 - Sam''s Natal (NTS)', 'sams_club', 'RN'),
('4944', '4944 - Sam''s Fortaleza Papicu (FZS)', 'sams_club', 'CE'),
('4947', '4947 - Sam''s Sertório Porto Alegre (PAS)', 'sams_club', 'RS'),
('4949', '4949 - Sam''s Ribeirão Preto (RBS)', 'sams_club', 'SP'),
('4951', '4951 - Sam''s São Bernardo do Campo (SDS)', 'sams_club', 'SP'),
('4953', '4953 - Sam''s Águas Claras (ACS)', 'sams_club', 'DF'),
('6230', '6230 - Sam''s Curitiba Atuba (CBS)', 'sams_club', 'PR'),
('6266', '6266 - Sam''s Santo Amaro (SAS)', 'sams_club', 'SP'),
('6268', '6268 - Sam''s Niterói (NIS)', 'sams_club', 'RJ'),
('6277', '6277 - Sam''s Rio Linha Amarela (RAS)', 'sams_club', 'RJ'),
('6278', '6278 - Sam''s Contagem (COS)', 'sams_club', 'MG'),
('6466', '6466 - Sam''s São Caetano do Sul (CES)', 'sams_club', 'SP'),
('6532', '6532 - Sam''s Santo André (SNS)', 'sams_club', 'SP'),
('6546', '6546 - Sam''s Osasco (OSS)', 'sams_club', 'SP'),
('BRI', 'BRI - Barra do Ribeiro Visconde (NBR)', 'super', 'RS'),
('CAP', 'CAP- Campinas', 'super', 'SP'),
('CIN', 'CIN- Indaiatuba', 'super', 'SP'),
('CIT', 'CIT- Itu', 'super', 'SP'),
('CMO', 'CMO- Morumbi', 'super', 'SP'),
('CNT', 'CNT- Interlagos', 'super', 'SP'),
('CPR', 'CPR SUPER CENTRAL PRAIA GRANDE', 'super', 'SP'),
('CRB', 'CRB- Rui Barbosa', 'super', 'SP'),
('CSA', 'CSA- Alphaville', 'super', 'SP'),
('CSB', 'CSB- São Bernardo', 'super', 'SP'),
('CST', 'CST- Salto', 'super', 'SP'),
('CTB', 'CTB- Taubaté II', 'super', 'SP'),
('CVA', 'CVA- Caçapava', 'super', 'SP'),
('CVN', 'CVN- Vinhedo', 'super', 'SP'),
('GSC', 'GSC- São Carlos - Vila C', 'super', 'SP'),
('GSF', 'GSF- São Carlos - Santa F', 'super', 'SP'),
('GSH', 'GSH - Guaíba Schell (NGS)', 'super', 'RS'),
('NAG', 'NAG  - Alegrete', 'super', 'RS'),
('NAP', 'NAP - Santo Antônio da Patrulha', 'super', 'RS'),
('NBC', 'NBC - Bacacheri', 'super', 'PR'),
('NBG', 'NBG - Bagé', 'super', 'RS'),
('NBL', 'NBL - Praia de Belas', 'super', 'RS'),
('NBT', 'NBT - Batel', 'super', 'PR'),
('NCB', 'NCB - Cidade Baixa', 'super', 'RS'),
('NCC', 'NCC - Capão da Canoa', 'super', 'RS'),
('NCH', 'NCH - Cachoeirinha', 'super', 'RS'),
('NCM', 'NCM - Comandante Araújo', 'super', 'PR'),
('NCN', 'NCN - Canoas', 'super', 'RS'),
('NCQ', 'NCQ - Camaquã', 'super', 'RS'),
('NCZ', 'NCZ - Santa Cruz do Sul', 'super', 'RS'),
('NDP', 'NDP - Dom Pedrito', 'super', 'RS'),
('NES', 'NES - Esteio', 'super', 'RS'),
('NGF', 'NGF - Gomes de Freitas', 'super', 'RS'),
('NGO', 'NGO - General Osório', 'super', 'PR'),
('NGU', 'NGU - Guaíba 20 Setembro', 'super', 'RS'),
('NGV', 'NGV - Gravataí Vila Branca', 'super', 'RS'),
('NIB', 'NIB - Imbé', 'super', 'RS'),
('NIJ', 'NIJ - Ijuí', 'super', 'RS'),
('NJA', 'NJA - Jardim das Américas', 'super', 'PR'),
('NJL', 'NJL - Jardim Leopoldina', 'super', 'RS'),
('NJU', 'NJU - Juvevê', 'super', 'PR'),
('NLC', 'NLC - Pelotas Lobo da C', 'super', 'RS'),
('NMA', 'NMA - Marechal Deodoro', 'super', 'PR'),
('NMD', 'NMD - Menino Deus', 'super', 'RS'),
('NMN', 'NMN - Montenegro', 'super', 'RS'),
('NNH', 'NNH - Novo Hamburgo (S135)', 'super', 'RS'),
('NOS', 'NOS - Osório', 'super', 'RS'),
('NPA', 'NPA - Pelotas Barão A', 'super', 'RS'),
('NPC', 'NPC - Pelotas Gonçalves', 'super', 'RS'),
('NRE', 'NRE - Rebouças', 'super', 'PR'),
('NRS', 'NRS - Rosário do Sul', 'super', 'RS'),
('NSA', 'NSA - Santo Ângelo', 'super', 'RS'),
('NSB', 'NSB - São Borja', 'super', 'RS'),
('NSG', 'NSG - São Gabriel', 'super', 'RS'),
('NSL', 'NSL - São Leopoldo', 'super', 'RS'),
('NSM', 'NSM - Santa Maria', 'super', 'RS'),
('NSR', 'NSR - Santa Rosa', 'super', 'RS'),
('NSS', 'NSS - Sapucaia do Sul', 'super', 'RS'),
('NST', 'NST - Santana', 'super', 'RS'),
('NTD', 'NTD - Tramandaí', 'super', 'RS'),
('NTE', 'NTE - Teresópolis', 'super', 'RS'),
('NTR', 'NTR - Torres', 'super', 'RS'),
('NVI', 'NVI - Viamão', 'super', 'RS'),
('NXL', 'NXL - Xangri-lá', 'super', 'RS'),
('PBM', 'PBM - Bom Motivo', 'super', 'DF'),
('PGE', 'PGE - Pelotas General Osório (NPO)', 'super', 'RS'),
('PL2', 'PL2 - Lago Sul', 'super', 'DF'),
('PN2', 'PN2 - Asa Norte II', 'super', 'DF'),
('PN4', 'PN4 - Asa Norte 512', 'super', 'DF'),
('PS1', 'PS1 - Asa Sul I', 'super', 'DF'),
('PS2', 'PS2 - Asa Sul II', 'super', 'DF'),
('SGR', 'SGR - Gramado (NGR)', 'super', 'RS'),
('WAF', 'WAF - Super Aflitos', 'super', 'PE'),
('WBA', 'WBA - Barra', 'super', 'BA'),
('WBE', 'WBE - Benfica', 'super', 'PE'),
('WBR', 'WBR - Super Boca do Rio (556)', 'super', 'BA'),
('WCC', 'WCC - Chame Chame', 'super', 'BA'),
('WCD', 'WCD - Candeias', 'super', 'BA'),
('WCG', 'WCG  - Conselheiro Aguiar', 'super', 'PE'),
('WCN', 'WCN - Canela', 'super', 'BA'),
('WDF', 'WDF - Domingos Ferreira', 'super', 'PE'),
('WEP', 'WEP - Epitácio Pessoa', 'super', 'PB'),
('WES', 'WES - Espinheiro', 'super', 'PE'),
('WFR', 'WFR - Farol', 'super', 'AL'),
('WIG', 'WIG - Itaigara', 'super', 'BA'),
('WJC', 'WJC - Jaboatão Candeias', 'super', 'PE'),
('WJD', 'WJD - Jardins', 'super', 'SE'),
('WJP', 'WJP - Jaboatão Piedade', 'super', 'PE'),
('WMP', 'WMP - Mini Politeama', 'super', 'BA'),
('WNZ', 'WNZ - Nazaré', 'super', 'BA'),
('WPA', 'WPA - Parque Amorim', 'super', 'PE'),
('WPF', 'WPF - Plataforma', 'super', 'BA'),
('WPI', 'WPI - Pituba', 'super', 'BA'),
('WPJ', 'WPJ - Pajuçara', 'super', 'AL'),
('WPT', 'WPT - Petrolina', 'super', 'PE'),
('WPV', 'WPV - Ponta Verde', 'super', 'AL'),
('WRE', 'WRE - Shopping Center Recife (WRC)', 'super', 'PE'),
('WRV', 'WRV - Rio Vermelho', 'super', 'BA'),
('WSF', 'WSF - São Francisco', 'super', 'MA'),
('WSN', 'WSN - Saneamento', 'super', 'SE'),
('WSR', 'WSR - São Rafael (1362)', 'super', 'BA'),
('WSS', 'WSS - Salvador Shopping', 'super', 'BA'),
('TAF', 'TAF - Todo Dia Afogados (B007)', 'todo_dia', 'PE'),
('TAM', 'TAM - Todo Dia Abreu e Lima III (B487)', 'todo_dia', 'PE'),
('TBC', 'TBC - Todo Dia Bancários (B109)', 'todo_dia', 'PB'),
('TBQ', 'TBQ - Todo Dia Boquim (B635)', 'todo_dia', 'SE'),
('TBU', 'TBU - Todo Dia Bultrins (B469)', 'todo_dia', 'PE'),
('TCA', 'TCA - Todo Dia Castro (Jd. Araucárias) (S381)', 'todo_dia', 'PR'),
('TCB', 'TCB - Todo Dia Castelo Branco (B505)', 'todo_dia', 'BA'),
('TCC', 'TCC - Todo Dia Conceição do Coité (B648)', 'todo_dia', 'BA'),
('TCF', 'TCF - Todo Dia Cosme de Farias (B575)', 'todo_dia', 'BA'),
('TCG', 'TCG - Hiper Todo Dia Campina Grande', 'todo_dia', 'PB'),
('TCN', 'TCN - Todo Dia Carpina (B002)', 'todo_dia', 'PE'),
('TCO', 'TCO - Todo Dia Cabo (B214)', 'todo_dia', 'PE'),
('TCZ', 'TCZ - Todo Dia Cruz das Almas (B539)', 'todo_dia', 'BA'),
('TDA', 'TDA - Todo Dia Dias D''Ávila (B586)', 'todo_dia', 'BA'),
('TDD', 'TDD - Todo Dia Dias D''Ávila (J. Brasil) (B647)', 'todo_dia', 'BA'),
('TEG', 'TEG - Todo Dia Eustáquio Gomes (B306)', 'todo_dia', 'AL'),
('TEP', 'TEP - Todo Dia Esplanada (B625)', 'todo_dia', 'BA'),
('TER', 'TER - Todo Dia Entre Rios (B634)', 'todo_dia', 'BA'),
('TEV', 'TEV - Todo Dia Canoas (Estância Velha) (S290)', 'todo_dia', 'RS'),
('TFT', 'TFT - Todo Dia São Leopoldo (Feitoria) (S314)', 'todo_dia', 'RS'),
('TGA', 'TGA - Todo Dia Gameleira (B486)', 'todo_dia', 'PE'),
('TGU', 'TGU - Hiper Todo Dia Garanhuns', 'todo_dia', 'PE'),
('TIJ', 'TIJ - Todo Dia Ipojuca (B447)', 'todo_dia', 'PE'),
('TIP', 'TIP - Todo Dia Itapecuru Mirim (Piçarra) (B308)', 'todo_dia', 'MA'),
('TLB', 'TLB - Todo Dia Liberdade (B512)', 'todo_dia', 'BA'),
('TLM', 'TLM - Todo Dia Limoeiro (B453)', 'todo_dia', 'PE'),
('TLU', 'TLU - Todo Dia Sta Lúcia (B458)', 'todo_dia', 'AL'),
('TMB', 'TMB - Todo Dia Muritiba (B637)', 'todo_dia', 'BA'),
('TMJ', 'TMJ - Todo Dia Mata São João (B636)', 'todo_dia', 'BA'),
('TND', 'TND - Todo Dia Nova Descoberta (B137)', 'todo_dia', 'PE'),
('TNZ', 'TNZ - Todo Dia Nazaré da Mata (B494)', 'todo_dia', 'PE'),
('TPB', 'TPB - Todo Dia Pernambués (B559)', 'todo_dia', 'BA'),
('TPE', 'TEP - Todo Dia Parobé (S333)', 'todo_dia', 'RS'),
('TPF', 'TPF - Todo Dia Alvorada (Passo do Feijó) (S304)', 'todo_dia', 'RS'),
('TPG', 'TPG - Todo Dia Ponta Grossa (Santa Paula) (S345)', 'todo_dia', 'PR'),
('TPJ', 'TPJ - Todo Dia Pojuca (B626)', 'todo_dia', 'BA'),
('TPL', 'TPL - Todo Dia Paulista (B058)', 'todo_dia', 'PE'),
('TPQ', 'TPQ - Todo Dia Sapucaia do Sul (Pasqualini) (S376)', 'todo_dia', 'RS'),
('TPR', 'TPR - Todo Dia Periperi (B572)', 'todo_dia', 'BA'),
('TRB', 'TRB - Todo Dia Canoas (Rio Branco) (S357)', 'todo_dia', 'RS'),
('TRP', 'TRP - Todo Dia Rio Pardo (S326)', 'todo_dia', 'RS'),
('TRR', 'TRR - Todo Dia Rio Real (B644)', 'todo_dia', 'BA'),
('TRV', 'TRV - Todo Dia Rodoviária - BA (B523)', 'todo_dia', 'BA'),
('TSA', 'TSA - Todo Dia Sapucaia do Sul (S332)', 'todo_dia', 'RS'),
('TSG', 'TSG - Todo Dia São Gonçalo dos Campos (B633)', 'todo_dia', 'BA'),
('TSM', 'TSM - Todo Dia Santo Amaro (B607)', 'todo_dia', 'BA'),
('TSO', 'TSO - Todo Dia Simões Filho (CIA I) (B620)', 'todo_dia', 'BA'),
('TSS', 'TSS - Todo Dia Sussuarana (B531)', 'todo_dia', 'BA'),
('TTA', 'TTA - Todo Dia Taquara (S293)', 'todo_dia', 'RS'),
('TTU', 'TTU - Todo Dia Timbaúba (B479)', 'todo_dia', 'PE'),
('TTV', 'TTV - Todo Dia Teotônio Vilela (B497)', 'todo_dia', 'AL'),
('TUP', 'TUP - Todo Dia União dos Palmares (B495)', 'todo_dia', 'AL'),
('TVG', 'TVG - Todo Dia Vargem Grande (B445)', 'todo_dia', 'MA'),
('TVZ', 'TVZ - Todo Dia Vera Cruz (B624)', 'todo_dia', 'BA'),
('1', '1 - Matriz ADM Atacadão', 'escritorio', 'SP'),
('2', '2 - Campo Grande AT', 'cd_atacadao', 'MS'),
('3', '3 - Campo Grande Cel Antonino', 'atacadao', 'MS'),
('6', '6 - Taipas', 'atacadao', 'SP'),
('7', '7 - Dourados', 'atacadao', 'MS'),
('8', '8 - Taguatinga AT', 'cd_atacadao', 'DF'),
('9', '9 - Maringá AT', 'cd_atacadao', 'PR'),
('14', '14 - Taguatinga Via Estádio', 'atacadao', 'DF'),
('15', '15 - Jandira', 'cd_atacadao', 'SP'),
('20', '20 - Santo Amaro', 'atacadao', 'SP'),
('21', '21 - Santo André Centro (615)', 'atacadao', 'SP'),
('30', '30 - Uberlândia', 'atacadao', 'MG'),
('31', '31 - Campo Grande Costa E Silva', 'atacadao', 'MS'),
('35', '35 - São Miguel', 'atacadao', 'SP'),
('39', '39 - Londrina Tiradentes', 'atacadao', 'PR'),
('42', '42 - Maringá Fernão Dias', 'atacadao', 'PR'),
('45', '45 - Tijucal (927)', 'atacadao', 'MT'),
('46', '46 - Santos', 'atacadao', 'SP'),
('47', '47 - Recife Iputinga', 'atacadao', 'PE'),
('48', '48 - Itaquera', 'atacadao', 'SP'),
('50', '50 - Olinda Pan Nordestina', 'atacadao', 'PE'),
('51', '51 - Natal Sul', 'atacadao', 'RN'),
('55', '55 - Jaboatão Prazeres', 'atacadao', 'PE'),
('56', '56 - Caruaru Petrópolis', 'atacadao', 'PE'),
('57', '57 - Parelheiros', 'atacadao', 'SP'),
('60', '60 - Vila Maria', 'atacadao', 'SP'),
('61', '61 - Brasília Asa Norte', 'atacadao', 'DF'),
('62', '62 - Natal Norte', 'atacadao', 'RN'),
('63', '63 - Automóvel Clube', 'atacadao', 'RJ'),
('65', '65 - Guadalupe', 'atacadao', 'RJ'),
('67', '67 - Nova Iguaçu Maria Da Luz', 'atacadao', 'RJ'),
('68', '68 - Aracaju BR', 'atacadao', 'SE'),
('69', '69 - Mossoró', 'atacadao', 'RN'),
('72', '72 - Porto Velho Rondônia', 'atacadao', 'RO'),
('75', '75 - Sapucaia Do Sul', 'atacadao', 'RS'),
('79', '79 - Feira Santana', 'atacadao', 'BA'),
('80', '80 - Fortaleza Aeroporto', 'atacadao', 'CE'),
('82', '82 - Juazeiro Norte São José', 'atacadao', 'CE'),
('87', '87 - Igarassu (187) AT', 'cd_atacadao', 'PE'),
('88', '88 - Porto Alegre Sertório', 'atacadao', 'RS'),
('92', '92 - Ribp.Anhanguera', 'atacadao', 'SP'),
('96', '96 - Ribeirão Preto AT', 'cd_atacadao', 'SP'),
('98', '98 - Maceió Aeroporto', 'atacadao', 'AL'),
('101', '101 - Palmas AT', 'cd_atacadao', 'TO'),
('102', '102 - Goytacazes Guarus', 'atacadao', 'RJ'),
('103', '103 - Vila Velha (129) AT', 'cd_atacadao', 'ES'),
('107', '107 - Gravataí Rs 118', 'atacadao', 'RS'),
('109', '109 - Aracaju AT', 'cd_atacadao', 'SE'),
('110', '110 - Fortaleza AT', 'cd_atacadao', 'CE'),
('111', '111 - Matriz CD/AT', 'cd_atacadao', 'SP'),
('113', '113 - São Luís', 'atacadao', 'MA'),
('114', '114 - João Pessoa AT', 'cd_atacadao', 'PB'),
('118', '118 - Manaus Grande Circular', 'atacadao', 'AM'),
('119', '119 - Manaus AT', 'cd_atacadao', 'AM'),
('120', '120 - Jacuí', 'atacadao', 'SP'),
('121', '121 - Santa Maria Camobi', 'atacadao', 'RS'),
('122', '122 - Pelotas Fragata', 'atacadao', 'RS'),
('123', '123 - Rio Grande', 'atacadao', 'RS'),
('124', '124 - Feira Santana (804) AT', 'cd_atacadao', 'BA'),
('125', '125 - Camboriú AT', 'cd_atacadao', 'SC'),
('126', '126 - Teresina Primavera', 'atacadao', 'PI'),
('127', '127 - Imperatriz', 'atacadao', 'MA'),
('130', '130 - Macaé', 'atacadao', 'RJ'),
('132', '132 - Novo Hamburgo Ideal', 'atacadao', 'RS'),
('133', '133 - Ipiranga', 'atacadao', 'SP'),
('135', '135 - Ponta grossa', 'atacadao', 'PR'),
('136', '136 - Santa cruz', 'atacadao', 'RJ'),
('137', '137 - Campo Grande Aeroporto', 'atacadao', 'MS'),
('138', '138 - Ananindeua BR', 'atacadao', 'PA'),
('141', '141 - Rio Branco', 'atacadao', 'AC'),
('142', '142 - Sapucaia AT', 'cd_atacadao', 'RS'),
('144', '144 - Caucaia (668)', 'atacadao', 'CE'),
('147', '147 - Juiz De Fora', 'atacadao', 'MG'),
('148', '148 - Arapiraca', 'atacadao', 'AL'),
('149', '149 - Manaus Cidade Nova', 'atacadao', 'AM'),
('150', '150 - Igarassu', 'atacadao', 'PE'),
('151', '151 - Itapevi', 'atacadao', 'SP'),
('152', '152 - Camaragibe', 'atacadao', 'PE'),
('153', '153 - Belém Icoaraci', 'atacadao', 'PA'),
('154', '154 - Belém AT', 'cd_atacadao', 'PA'),
('155', '155 - Imperatriz AT', 'cd_atacadao', 'MA'),
('157', '157 - Cabo Frio', 'atacadao', 'RJ'),
('158', '158 - Fortaleza Eusébio', 'atacadao', 'CE'),
('159', '159 - Macapá Jk', 'atacadao', 'AP'),
('160', '160 - Teresina Boa vista', 'atacadao', 'PI'),
('162', '162 - Santa Cruz AT', 'cd_atacadao', 'RJ'),
('167', '167 - Betim', 'atacadao', 'MG'),
('168', '168 - Itajaí-As', 'atacadao', 'SC'),
('170', '170 - Governador Valadares', 'atacadao', 'MG'),
('171', '171 - Londrina Ceasa', 'atacadao', 'PR'),
('172', '172 - Cascavel', 'atacadao', 'PR'),
('173', '173 - Sobral', 'atacadao', 'CE'),
('174', '174 - Duque De Caxias', 'atacadao', 'RJ'),
('177', '177 - Pinhais AT', 'cd_atacadao', 'PR'),
('178', '178 - Foz Do Iguaçu Ponte Da Amizade', 'atacadao', 'PR'),
('179', '179 - Boa Vista', 'atacadao', 'RR'),
('180', '180 - Contagem BR - 040', 'atacadao', 'MG'),
('181', '181 - Betim AT', 'cd_atacadao', 'MG'),
('182', '182 - Santarém', 'atacadao', 'PA'),
('183', '183 - Jacareí AT', 'cd_atacadao', 'SP'),
('185', '185 - Santo Antônio Jesus', 'atacadao', 'BA'),
('186', '186 - Vilhena', 'atacadao', 'RO'),
('188', '188 - Manaus Educando', 'atacadao', 'AM'),
('189', '189 - Fortaleza Osório', 'atacadao', 'CE'),
('193', '193 - Itaboraí', 'atacadao', 'RJ'),
('198', '198 - Estrela', 'atacadao', 'RS'),
('200', '200 - Marabá', 'atacadao', 'PA'),
('201', '201 - Ji Paraná', 'atacadao', 'RO'),
('202', '202 - São Gonçalo', 'atacadao', 'RJ'),
('203', '203 - Chapecó Atílio Fontana', 'atacadao', 'SC'),
('207', '207 - Resende', 'atacadao', 'RJ'),
('210', '210 - Jacarepaguá', 'atacadao', 'RJ'),
('212', '212 - Blumenau', 'atacadao', 'SC'),
('213', '213 - Porto Velho AT', 'cd_atacadao', 'RO'),
('215', '215 - Belém Portal', 'atacadao', 'PA');

insert into stores (code, name, type, state) values
('216', '216 - Maceió AT', 'cd_atacadao', 'AL'),
('217', '217 - Maceió Praia', 'atacadao', 'AL'),
('222', '222 - São José Dos Pinhais', 'atacadao', 'PR'),
('224', '224 - Parnamirim AT', 'cd_atacadao', 'RN'),
('226', '226 - Aricanduva', 'atacadao', 'SP'),
('227', '227 - Maringá Colombo', 'atacadao', 'PR'),
('228', '228 - Recife Boa Viagem', 'atacadao', 'PE'),
('229', '229 - Interlagos', 'atacadao', 'SP'),
('230', '230 - Castanhal', 'atacadao', 'PA'),
('237', '237 - Três Lagoas', 'atacadao', 'MS'),
('238', '238 - Ananindeua Castanheira', 'atacadao', 'PA'),
('240', '240 - Serra Talhada', 'atacadao', 'PE'),
('241', '241 - Uberaba', 'atacadao', 'MG'),
('242', '242 - Viamão', 'atacadao', 'RS'),
('243', '243 - Caruaru Polo', 'atacadao', 'PE'),
('244', '244 - Petrolina', 'atacadao', 'PE'),
('245', '245 - Parnamirim', 'atacadao', 'RN'),
('246', '246 - Curitiba Bairro Alto', 'atacadao', 'PR'),
('247', '247 - Realengo', 'atacadao', 'RJ'),
('248', '248 - Boa Vista AT', 'cd_atacadao', 'RR'),
('249', '249 - Benfica', 'atacadao', 'RJ'),
('251', '251 - Inajar De Souza', 'atacadao', 'SP'),
('253', '253 - Picos', 'atacadao', 'PI'),
('254', '254 - Criciúma', 'atacadao', 'SC'),
('255', '255 - Macapá Zona Norte', 'atacadao', 'AP'),
('256', '256 - Macapá AT', 'cd_atacadao', 'AP'),
('258', '258 - Cambé', 'atacadao', 'PR'),
('259', '259 - Nova Friburgo', 'atacadao', 'RJ'),
('260', '260 - Guarapuava Centro', 'atacadao', 'PR'),
('261', '261 - Umuarama Av. Portugal', 'atacadao', 'PR'),
('262', '262 - Cotia Raposo Km 21', 'atacadao', 'SP'),
('264', '264 - Paulista', 'atacadao', 'PE'),
('265', '265 - Teresina AT', 'cd_atacadao', 'PI'),
('268', '268 - Bragança Paulista', 'atacadao', 'SP'),
('269', '269 - Anchieta', 'atacadao', 'SP'),
('270', '270 - Rio Das Ostras', 'atacadao', 'RJ'),
('273', '273 - Maceió Petrópolis', 'atacadao', 'AL'),
('274', '274 - Aracaju Tancredo Neves', 'atacadao', 'SE'),
('275', '275 - Bonsucesso', 'atacadao', 'RJ'),
('276', '276 - Ananindeua Coqueiro', 'atacadao', 'PA'),
('278', '278 - Mendanha', 'atacadao', 'RJ'),
('280', '280 - Garanhuns', 'atacadao', 'PE'),
('281', '281 - Manaus Moderna', 'atacadao', 'AM'),
('282', '282 - Joinville', 'atacadao', 'SC'),
('283', '283 - São Leopoldo', 'atacadao', 'RS'),
('284', '284 - Caxias Do Sul', 'atacadao', 'RS'),
('286', '286 - Manaus Japiim', 'atacadao', 'AM'),
('288', '288 - Porto Alegre Ceasa', 'atacadao', 'RS'),
('289', '289 - Volta Redonda Vila Rica', 'atacadao', 'RJ'),
('290', '290 - Florianópolis Jk', 'atacadao', 'SC'),
('291', '291 - Nova Iguaçu Comendador Soares', 'atacadao', 'RJ'),
('292', '292 - Goytacazes Parque Santo Amaro', 'atacadao', 'RJ'),
('293', '293 - Recife Av Recife', 'atacadao', 'PE'),
('294', '294 - Barra', 'atacadao', 'RJ'),
('295', '295 - Brasília Sia', 'atacadao', 'DF'),
('297', '297 - Gama', 'atacadao', 'DF'),
('298', '298 - Teresina Ilhotas', 'atacadao', 'PI'),
('300', '300 - Curitiba Parolin', 'atacadao', 'PR'),
('303', '303 - São José Educandário', 'atacadao', 'SC'),
('304', '304 - Fortaleza BR 116', 'atacadao', 'CE'),
('305', '305 - Fortaleza Barra Do Ceará', 'atacadao', 'CE'),
('306', '306 - Santarém AT', 'cd_atacadao', 'PA'),
('308', '308 - Rio Branco', 'atacadao', 'AC'),
('312', '312 - Jaboatão Centro', 'atacadao', 'PE'),
('314', '314 - Biguaçu', 'atacadao', 'SC'),
('316', '316 - Santa Cruz Do Capibaribe', 'atacadao', 'PE'),
('319', '319 - Marica', 'atacadao', 'RJ'),
('320', '320 - Recanto Das Emas', 'atacadao', 'DF'),
('322', '322 - Montes Claros AT', 'cd_atacadao', 'MG'),
('323', '323 - Palmares', 'atacadao', 'PE'),
('326', '326 - Abaetetuba', 'atacadao', 'PA'),
('328', '328 - Belo Jardim', 'atacadao', 'PE'),
('329', '329 - Caicó', 'atacadao', 'RN'),
('335', '335 - Redenção', 'atacadao', 'PA'),
('336', '336 - Cabo Frio Tamoios', 'atacadao', 'RJ'),
('337', '337 - Sete Lagoas', 'atacadao', 'MG'),
('338', '338 - Lanchonete Matriz Tatuapé', 'todo_dia', null),
('340', '340 - Tatuapé', 'atacadao', 'SP'),
('343', '343 - Taguatinga Pistão Sul', 'atacadao', 'DF'),
('347', '347 - Itaquaquecetuba', 'atacadao', 'SP'),
('349', '349 - Sapucaia', 'cd_atacadao', 'RS'),
('350', '350 - Sobradinho', 'atacadao', 'DF'),
('355', '355 - Campo Grande Centenário', 'atacadao', 'MS'),
('356', '356 - São Lourenço Da Mata', 'atacadao', 'PE'),
('357', '357 - Vitória De Santo Antão', 'atacadao', 'PE'),
('358', '358 - Ribeirão Preto AT', 'cd_atacadao', 'SP'),
('359', '359 - Boa Vista Shopping', 'atacadao', 'RR'),
('364', '364 - Rios das Pedras (Aricanduva II)', 'atacadao', 'SP'),
('365', '365 - Santos Porto', 'atacadao', 'SP'),
('366', '366 - Suzano Índio Tibiriçá', 'todo_dia', null),
('367', '367 - Mogi das Cruzes Moderno', 'todo_dia', null),
('452', '452 - Guarulhos AT', 'cd_atacadao', 'SP'),
('611', '611 - Araçagi', 'atacadao', 'MA'),
('612', '612 - Carapicuíba Km 21 (43)', 'atacadao', 'SP'),
('614', '614 - Limeira Anhanguera (32)', 'atacadao', 'SP'),
('615', '615 - Santo André Centro (21)', 'atacadao', 'SP'),
('616', '616 - Atibaia (104)', 'atacadao', 'SP'),
('617', '617 - Guarulhos Aeroporto (49)', 'atacadao', 'SP'),
('618', '618 - Salvador Garibaldi (BSG)', 'atacadao', 'BA'),
('619', '619 - Fortaleza Fátima (BFT)', 'atacadao', 'CE'),
('620', '620 - Fortaleza Maraponga (FOR)', 'atacadao', 'CE'),
('621', '621 - Limeira Centro (713)', 'atacadao', 'SP'),
('622', '622 - Itanhaém (235)', 'atacadao', 'SP'),
('623', '623 - Guarulhos Centro (715)', 'atacadao', 'SP'),
('624', '624 - Catanduva (711)', 'atacadao', 'SP'),
('625', '625 - Americana (333)', 'atacadao', 'SP'),
('626', '626 - Ribeirão Preto Anhanguera (92)', 'atacadao', 'SP'),
('627', '627 - Itaquaquecetuba (347)', 'atacadao', 'SP'),
('628', '628 - Guarulhos Bonsucesso (352)', 'atacadao', 'SP'),
('629', '629 - Guarulhos Dutra (18)', 'atacadao', 'SP'),
('630', '630 - Marília (140)', 'atacadao', 'SP'),
('631', '631 - Mauá Itapark (97)', 'atacadao', 'SP'),
('632', '632 - Hortolândia (348)', 'atacadao', 'SP'),
('633', '633 - Jundiaí (194)', 'atacadao', 'SP'),
('634', '634 - Taboão Da Serra Centro (22)', 'atacadao', 'SP'),
('635', '635 - Jacareí Dutra (84)', 'atacadao', 'SP'),
('636', '636 - Santo André Estado (164)', 'atacadao', 'SP'),
('637', '637 - Osasco Centro (223)', 'atacadao', 'SP'),
('638', '638 - Rio Claro (332)', 'atacadao', 'SP'),
('639', '639 - São Caetano Do Sul (327)', 'atacadao', 'SP'),
('640', '640 - Diadema Cupecê (339)', 'atacadao', 'SP'),
('641', '641 - Ribeirão Via Norte (209)', 'atacadao', 'SP'),
('642', '642 - Sorocaba Itavuvu (318)', 'atacadao', 'SP'),
('643', '643 - Ourinhos (331)', 'atacadao', 'SP'),
('644', '644 - São Vicente (239)', 'atacadao', 'SP'),
('645', '645 - Botucatu (345)', 'atacadao', 'SP'),
('646', '646 - Caraguatatuba (195)', 'atacadao', 'SP'),
('647', '647 - Sorocaba Dom Aguirre (163)', 'atacadao', 'SP'),
('648', '648 - Araçatuba (257)', 'atacadao', 'SP'),
('649', '649 - Osasco Yolanda (310)', 'atacadao', 'SP'),
('650', '650 - Jandira (190)', 'atacadao', 'SP'),
('651', '651 - Barretos (236)', 'atacadao', 'SP'),
('652', '652 - Cotia Raposo Km 21 (262)', 'atacadao', 'SP'),
('653', '653 - Taubaté (143)', 'atacadao', 'SP'),
('654', '654 - Carapicuíba Gopiuva (321)', 'atacadao', 'SP'),
('655', '655 - Barueri (287)', 'atacadao', 'SP'),
('656', '656 - Poa (330)', 'atacadao', 'SP'),
('657', '657 - Sorocaba Campolim (218)', 'atacadao', 'SP'),
('658', '658 - Indaiatuba (266)', 'atacadao', 'SP'),
('659', '659 - São Bernardo Demarchi (324)', 'atacadao', 'SP'),
('660', '660 - Presidente Prudente Raposo (175)', 'atacadao', 'SP'),
('661', '661 - Bauru (139)', 'atacadao', 'SP'),
('662', '662 - Campinas Jd. Yeda (105)', 'atacadao', 'SP'),
('663', '663 - Campinas Dom Pedro (23)', 'atacadao', 'SP'),
('664', '664 - Itapevi (34|151)', 'atacadao', 'SP'),
('665', '665 - Vila Velha (78)', 'atacadao', 'ES'),
('666', '666 - Patos (199)', 'atacadao', 'PB'),
('667', '667 - Campina Grande Manoel Tavares (89| 885)', 'atacadao', 'PB'),
('669', '669 - Campina Grande Itararé (279)', 'atacadao', 'PB'),
('670', '670 - Serra (156)', 'atacadao', 'ES'),
('671', '671 - Palmas Rodoviária (90)', 'atacadao', 'TO'),
('672', '672 - Contagem Shopping (710)', 'atacadao', 'MG'),
('673', '673 - Gurupi (344)', 'atacadao', 'TO'),
('674', '674 - Araguaína Filadelfia (176)', 'atacadao', 'TO'),
('675', '675 - Diadema Serraria (353)', 'atacadao', 'SP'),
('676', '676 - Mauá João Ramalho (271)', 'atacadao', 'SP'),
('677', '677 - Campinas Dunlop (134)', 'atacadao', 'SP'),
('678', '678 - Ribeirão Pires (250)', 'atacadao', 'SP'),
('679', '679 - Belford Roxo (CBR)', 'atacadao', 'RJ'),
('680', '680 - Cambuci (SPC)', 'atacadao', 'SP'),
('681', '681 - Manilha (RJM)', 'atacadao', 'RJ'),
('682', '682 - São Bernardo Centro (714)', 'atacadao', 'SP'),
('683', '683 - Palmas Parque Cesamar (277)', 'atacadao', 'TO'),
('684', '684 - Pampulha (720)', 'atacadao', 'MG'),
('685', '685 - Franca Av. Rio Negro (71)', 'atacadao', 'SP'),
('687', '687 - Osasco Bonança', 'atacadao', 'SP'),
('688', '688 - João Pessoa BR (74)', 'atacadao', 'PB'),
('689', '689 - Santa Rita (146)', 'atacadao', 'PB'),
('691', '691 - Pilares (719)', 'atacadao', 'RJ'),
('692', '692 - Recife Casa Amarela (WCA )', 'atacadao', 'PE'),
('693', '693 - Jaboatão Candeias', 'atacadao', 'PE'),
('694', '694 - Recife Arruda (WAR)', 'atacadao', 'PE'),
('695', '695 - Salvador Barra (WBA)', 'atacadao', 'BA'),
('696', '696 - Salvador Pituba (WPI)', 'atacadao', 'BA'),
('697', '697 - Pacaembu (716)', 'atacadao', 'SP'),
('699', '699 - Bangu', 'atacadao', 'RJ'),
('700', '700 - Central Wmb', 'atacadao', 'SP'),
('702', '702 - Palmas Teotônio', 'atacadao', 'TO'),
('705', '705 - Araguaína BR153', 'atacadao', 'TO'),
('706', '706 - Maceió Jatiuca', 'atacadao', 'AL'),
('712', '712 - Patos De Minas', 'atacadao', 'MG'),
('717', '717 - Goiânia Flamboyant', 'atacadao', 'GO'),
('718', '718 - Indianópolis', 'atacadao', 'SP'),
('720', '720 - Pampulha (684)', 'atacadao', 'MG'),
('721', '721 - Vila Guilherme', 'atacadao', 'SP'),
('730', '730 - Guarujá (53)', 'atacadao', 'SP'),
('731', '731 - Praia Grande (17)', 'atacadao', 'SP'),
('732', '732 - Suzano Centro (54)', 'atacadao', 'SP'),
('733', '733 - Ferraz Vasconcelos (184)', 'atacadao', 'SP'),
('734', '734 - Tamboré (196)', 'atacadao', 'SP'),
('735', '735 - São Carlos (221)', 'atacadao', 'SP'),
('736', '736 - Sumaré (309)', 'atacadao', 'SP'),
('737', '737 - Sj Campos Jk (91)', 'atacadao', 'SP'),
('738', '738 - Araraquara (145)', 'atacadao', 'SP'),
('739', '739 - Cotia Centro (59)', 'atacadao', 'SP'),
('740', '740 - Cachoeirinha (BCH)', 'atacadao', 'RS'),
('741', '741 - Itaparica (WIA)', 'atacadao', 'BA'),
('742', '742 - Itapuã (WIT)', 'atacadao', 'BA'),
('743', '743 - Várzea Paulista (317)', 'atacadao', 'SP'),
('744', '744 - Sj Campos Dutra (272)', 'atacadao', 'SP'),
('745', '745 - João Pessoa Bessa', 'atacadao', 'PB'),
('746', '746 - Paulínia', 'atacadao', 'SP'),
('800', '800 - Central Wms', 'atacadao', 'SP'),
('801', '801 - Santo André WMS', 'atacadao', 'SP'),
('802', '802 - Tijucal (81) AT', 'cd_atacadao', 'MT'),
('803', '803 - Goiânia (232) AT', 'cd_atacadao', 'GO'),
('805', '805 - Vitória da Conquista (94) AT', 'cd_atacadao', 'BA'),
('806', '806 - Pirajá (341) AT', 'cd_atacadao', 'BA'),
('811', '811 - Santo André Capuava', 'atacadao', 'SP'),
('812', '812 - Diadema Canhema', 'atacadao', 'SP'),
('813', '813 - São José Dos Campos Shopping', 'atacadao', 'SP'),
('814', '814 - Jacareí Centro', 'atacadao', 'SP'),
('815', '815 - Volta Redonda São Geraldo', 'atacadao', 'RJ'),
('816', '816 - Itu', 'atacadao', 'SP'),
('817', '817 - Goiânia Av. Independência', 'atacadao', 'GO'),
('818', '818 - Araras', 'atacadao', 'SP'),
('819', '819 - Piracicaba Piracicamirim', 'atacadao', 'SP'),
('820', '820 - Vitória Conquista Brumado', 'atacadao', 'BA'),
('821', '821 - Umuarama Parque Danielle', 'atacadao', 'PR'),
('822', '822 - Mogi-Guacu', 'atacadao', 'SP'),
('823', '823 - Vitória', 'atacadao', 'ES'),
('824', '824 - Lauro De Freitas Caji', 'atacadao', 'BA'),
('825', '825 - Pinhais', 'atacadao', 'PR'),
('826', '826 - Canoas', 'atacadao', 'RS'),
('827', '827 - Assis', 'atacadao', 'SP'),
('828', '828 - Juazeiro Do Norte Triângulo', 'atacadao', 'CE'),
('829', '829 - Campina Grande Floriano Peixoto', 'atacadao', 'PB'),
('830', '830 - Feira Pedra Do Descanso', 'atacadao', 'BA'),
('831', '831 - Bagé', 'atacadao', 'RS'),
('832', '832 - Olinda Casa Caiada', 'atacadao', 'PE'),
('833', '833 - Presidente Prudente Monte Alto', 'atacadao', 'SP'),
('834', '834 - Curitiba Boqueirão', 'atacadao', 'PR'),
('835', '835 - Salvador Cabula (BCB)', 'atacadao', 'BA'),
('836', '836 - Maracanaú', 'atacadao', 'CE'),
('837', '837 - Curitiba Santa Felicidade', 'atacadao', 'PR'),
('838', '838 - Porto Alegre Vila Nova', 'atacadao', 'RS'),
('839', '839 - Curitiba Av Das Torres (41)', 'atacadao', 'PR'),
('840', '840 - Fortaleza Papicu', 'atacadao', 'CE'),
('841', '841 - Salvador Pau Da Lima', 'atacadao', 'BA'),
('842', '842 - Natal Prudente De Morais', 'atacadao', 'RN'),
('843', '843 - Lages', 'atacadao', 'SC'),
('844', '844 - Toledo', 'atacadao', 'PR'),
('845', '845 - Camaçari Centro', 'atacadao', 'BA'),
('846', '846 - Florianópolis Via Expressa', 'atacadao', 'SC'),
('847', '847 - Porto Alegre Humaitá', 'atacadao', 'RS'),
('848', '848 - Curitiba Fazendinha', 'atacadao', 'PR'),
('849', '849 - Teresina Ladeira Do Uruguai', 'atacadao', 'PI'),
('850', '850 - Chapecó Fernando Machado', 'atacadao', 'SC'),
('851', '851 - Salvador Mares', 'atacadao', 'BA'),
('852', '852 - Sapiranga', 'atacadao', 'RS'),
('853', '853 - Curitiba Xaxim', 'atacadao', 'PR'),
('854', '854 - Alvorada', 'atacadao', 'RS'),
('855', '855 - Curitiba Pinheirinho', 'atacadao', 'PR'),
('856', '856 - Uruguaiana', 'atacadao', 'RS'),
('857', '857 - Santa Maria Patronato', 'atacadao', 'RS'),
('858', '858 - Santana Do Livramento', 'atacadao', 'RS'),
('859', '859 - Curitiba Arthur Bernardes', 'atacadao', 'PR'),
('860', '860 - Curitiba Boa Vista', 'atacadao', 'PR'),
('861', '861 - Gravataí Av Dorival Cândido', 'atacadao', 'RS'),
('862', '862 - Aracaju Goncalo Prado', 'atacadao', 'SE'),
('863', '863 - Maxxi Foz Do Iguaçu Jk', 'atacadao', 'PR'),
('864', '864 - Maxxi Franca Jd Francano', 'atacadao', 'SP'),
('865', '865 - Pelotas Centro', 'atacadao', 'RS'),
('866', '866 - Santo Ângelo', 'atacadao', 'RS'),
('867', '867 - Porto Alegre Sarandi', 'atacadao', 'RS'),
('868', '868 - Lajeado', 'atacadao', 'RS'),
('869', '869 - Santa Cruz Do Sul', 'atacadao', 'RS'),
('870', '870 - Cabo De Santo Agostinho', 'atacadao', 'PE'),
('871', '871 - Fortaleza Vila Peri', 'atacadao', 'CE'),
('872', '872 - Taboão Da Serra Rua Do Tesouro', 'atacadao', 'SP'),
('873', '873 - Guarapuava BR 277', 'atacadao', 'PR'),
('874', '874 - Maxxi Mossoró', 'atacadao', 'RN'),
('875', '875 - Maxxi Parnamirim', 'atacadao', 'RN'),
('876', '876 - Novo Hamburgo Ouro Branco', 'atacadao', 'RS'),
('877', '877 - Maxxi Itajaí', 'atacadao', 'SC'),
('878', '878 - Maxxi Brasília', 'atacadao', 'DF'),
('879', '879 - Maxxi Criciúma', 'atacadao', 'SC'),
('880', '880 - Maxxi Indaiatuba', 'atacadao', 'SP'),
('881', '881 - Maxxi Arapiraca', 'atacadao', 'AL'),
('882', '882 - Maxxi Salvador Bonoco', 'atacadao', 'BA'),
('883', '883 - Maxxi Rio Grande', 'atacadao', 'RS'),
('884', '884 - Maxxi Caxias Do Sul', 'atacadao', 'RS'),
('886', '886 - Rondonópolis Centro (44)', 'atacadao', 'MT'),
('887', '887 - Juazeiro (73)', 'atacadao', 'BA'),
('888', '888 - Rondonópolis Parque Universitário (351)', 'atacadao', 'MT'),
('889', '889 - Cuiaba Miguel Sutil (285)', 'atacadao', 'MT'),
('890', '890 - Cuiabá Chapada (128)', 'atacadao', 'MT'),
('891', '891 - Cuiabá CPA (296)', 'atacadao', 'MT'),
('892', '892 - Lucas Rio Verde (197)', 'atacadao', 'MT'),
('893', '893 - Primavera Do Leste (315)', 'atacadao', 'MT'),
('894', '894 - Vitória Conquista Presid Dutra (83 |805)', 'atacadao', 'BA'),
('895', '895 - Várzea Grande (169)', 'atacadao', 'MT'),
('896', '896 - Valença (325)', 'atacadao', 'BA'),
('897', '897 - Barra Do Garças (208)', 'atacadao', 'MT'),
('898', '898 - Tangará Da Serra (205)', 'atacadao', 'MT'),
('899', '899 - Sorriso (334)', 'atacadao', 'MT'),
('900', '900 - Valparaíso (77)', 'atacadao', 'GO'),
('901', '901 - Formosa (346)', 'atacadao', 'GO'),
('902', '902 - Santo Antônio De Jesus (185)', 'atacadao', 'BA'),
('903', '903 - Anápolis (161)', 'atacadao', 'GO');

insert into stores (code, name, type, state) values
('904', '904 - Itumbiara (231)', 'atacadao', 'GO'),
('905', '905 - Sinop (70)', 'atacadao', 'MT'),
('906', '906 - Ilhéus BR (115)', 'atacadao', 'BA'),
('907', '907 - Lauro De Freitas Portão (52)', 'atacadao', 'BA'),
('908', '908 - Feira Subaé (191)', 'atacadao', 'BA'),
('909', '909 - Simões Filho (225)', 'atacadao', 'BA'),
('910', '910 - Teixeira De Freitas (206)', 'atacadao', 'BA'),
('911', '911 - Eunápolis (93)', 'atacadao', 'BA'),
('912', '912 - Porto Seguro (263)', 'atacadao', 'BA'),
('913', '913 - Irecê (233)', 'atacadao', 'BA'),
('914', '914 - Feira Morada Das Arvores (66)', 'atacadao', 'BA'),
('915', '915 - Camaçari Via Parafuso (165)', 'atacadao', 'BA'),
('916', '916 - Salvador Acm (313)', 'atacadao', 'BA'),
('917', '917 - Salvador Cajazeiras (58)', 'atacadao', 'BA'),
('918', '918 - Salvador Bonoco (252)', 'atacadao', 'BA'),
('919', '919 - Salvador Barros Reis (16)', 'atacadao', 'BA'),
('920', '920 - Salvador Iguatemi (301)', 'atacadao', 'BA'),
('921', '921 - Salvador Mata Escura (342)', 'atacadao', 'BA'),
('922', '922 - Rio Verde (117)', 'atacadao', 'GO'),
('923', '923 - Salvador Trobogy (311)', 'atacadao', 'BA'),
('924', '924 - Alagoinhas (192)', 'atacadao', 'BA'),
('925', '925 - Salvador Pirajá (302)', 'atacadao', 'BA'),
('926', '926 - Barreiras (99)', 'atacadao', 'BA'),
('927', '927 - Cuiabá Tijucal (45)', 'atacadao', 'MT'),
('928', '928 - Cuiabá Porto (28)', 'atacadao', 'MT'),
('929', '929 - Goiânia Goiás Norte (64)', 'atacadao', 'GO'),
('930', '930 - Goiânia Perimetral (307)', 'atacadao', 'GO'),
('931', '931 - Aparecida De Goiânia BR 153 (299)', 'atacadao', 'GO'),
('932', '932 - Ilhéus Praia (354)', 'atacadao', 'BA'),
('933', '933 - Feira Santana Empresa (804| 79)', 'atacadao', 'BA'),
('934', '934 - Lauro Freitas Empresa (95)', 'atacadao', 'BA'),
('935', '935 - Aparecida De Goiânia Vera Cruz (131)', 'atacadao', 'GO'),
('936', '936 - Goiânia Romeiros (214)', 'atacadao', 'GO'),
('937', '937 - Penha (SPH)', 'atacadao', 'SP'),
('938', '938 - Pirituba (BPI)', 'atacadao', 'SP'),
('939', '939 - Vila Lobos (SPV)', 'atacadao', 'SP'),
('940', '940 - Mogi Das Cruzes Centro (204)', 'atacadao', 'SP'),
('941', '941 - Itapecerica Da Serra (211)', 'atacadao', 'SP'),
('942', '942 - Brotas (WBT)', 'atacadao', 'BA'),
('943', '943 - São Bernardo Piraporinha (86)', 'atacadao', 'SP'),
('944', '944 - São José Rio Preto - Falavina (219)', 'atacadao', 'SP'),
('945', '945 - Mogi Mirim (267)', 'atacadao', 'SP'),
('946', '946 - Piracicaba Sta Terezinha (85)', 'atacadao', 'SP'),
('947', '947 - Guaratinguetá (234)', 'atacadao', 'SP'),
('948', '948 - Santa Bárbara Doeste (166)', 'atacadao', 'SP'),
('949', '949 - São José Rio Preto - America (4)', 'atacadao', 'SP');

